// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/usecase/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "cityhawk/backend/internal/user/model"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockUserReader is a mock of UserReader interface.
type MockUserReader struct {
	ctrl     *gomock.Controller
	recorder *MockUserReaderMockRecorder
}

// MockUserReaderMockRecorder is the mock recorder for MockUserReader.
type MockUserReaderMockRecorder struct {
	mock *MockUserReader
}

// NewMockUserReader creates a new mock instance.
func NewMockUserReader(ctrl *gomock.Controller) *MockUserReader {
	mock := &MockUserReader{ctrl: ctrl}
	mock.recorder = &MockUserReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReader) EXPECT() *MockUserReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserReader) GetByID(ctx context.Context, id string) (model.User, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserReaderMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserReader)(nil).GetByID), ctx, id)
}

// MockRefreshSessionRepository is a mock of RefreshSessionRepository interface.
type MockRefreshSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshSessionRepositoryMockRecorder
}

// MockRefreshSessionRepositoryMockRecorder is the mock recorder for MockRefreshSessionRepository.
type MockRefreshSessionRepositoryMockRecorder struct {
	mock *MockRefreshSessionRepository
}

// NewMockRefreshSessionRepository creates a new mock instance.
func NewMockRefreshSessionRepository(ctrl *gomock.Controller) *MockRefreshSessionRepository {
	mock := &MockRefreshSessionRepository{ctrl: ctrl}
	mock.recorder = &MockRefreshSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshSessionRepository) EXPECT() *MockRefreshSessionRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockRefreshSessionRepository) Consume(ctx context.Context, refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockRefreshSessionRepositoryMockRecorder) Consume(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Consume), ctx, refreshToken)
}

// Revoke mocks base method.
func (m *MockRefreshSessionRepository) Revoke(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshSessionRepositoryMockRecorder) Revoke(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Revoke), ctx, refreshToken)
}

// Store mocks base method.
func (m *MockRefreshSessionRepository) Store(ctx context.Context, refreshToken, userID string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, refreshToken, userID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockRefreshSessionRepositoryMockRecorder) Store(ctx, refreshToken, userID, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRefreshSessionRepository)(nil).Store), ctx, refreshToken, userID, expiresAt)
}

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// GenerateOpaqueToken mocks base method.
func (m *MockTokenService) GenerateOpaqueToken(size int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateOpaqueToken", size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateOpaqueToken indicates an expected call of GenerateOpaqueToken.
func (mr *MockTokenServiceMockRecorder) GenerateOpaqueToken(size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateOpaqueToken", reflect.TypeOf((*MockTokenService)(nil).GenerateOpaqueToken), size)
}

// SignAccessToken mocks base method.
func (m *MockTokenService) SignAccessToken(u model.User, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignAccessToken", u, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignAccessToken indicates an expected call of SignAccessToken.
func (mr *MockTokenServiceMockRecorder) SignAccessToken(u, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignAccessToken", reflect.TypeOf((*MockTokenService)(nil).SignAccessToken), u, ttl)
}
