// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/usecase/auth_flow.go

// Package mocks is a generated GoMock package.
package mocks

import (
	model "cityhawk/backend/internal/auth/model"
	model0 "cityhawk/backend/internal/user/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthUserRepository is a mock of AuthUserRepository interface.
type MockAuthUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUserRepositoryMockRecorder
}

// MockAuthUserRepositoryMockRecorder is the mock recorder for MockAuthUserRepository.
type MockAuthUserRepositoryMockRecorder struct {
	mock *MockAuthUserRepository
}

// NewMockAuthUserRepository creates a new mock instance.
func NewMockAuthUserRepository(ctrl *gomock.Controller) *MockAuthUserRepository {
	mock := &MockAuthUserRepository{ctrl: ctrl}
	mock.recorder = &MockAuthUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUserRepository) EXPECT() *MockAuthUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthUserRepository) Create(ctx context.Context, u model0.User) (model0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(model0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthUserRepositoryMockRecorder) Create(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthUserRepository)(nil).Create), ctx, u)
}

// GetByEmail mocks base method.
func (m *MockAuthUserRepository) GetByEmail(ctx context.Context, email string) (model0.User, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(model0.User)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockAuthUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockAuthUserRepository)(nil).GetByEmail), ctx, email)
}

// MockPasswordService is a mock of PasswordService interface.
type MockPasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordServiceMockRecorder
}

// MockPasswordServiceMockRecorder is the mock recorder for MockPasswordService.
type MockPasswordServiceMockRecorder struct {
	mock *MockPasswordService
}

// NewMockPasswordService creates a new mock instance.
func NewMockPasswordService(ctrl *gomock.Controller) *MockPasswordService {
	mock := &MockPasswordService{ctrl: ctrl}
	mock.recorder = &MockPasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordService) EXPECT() *MockPasswordServiceMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockPasswordService) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordServiceMockRecorder) Hash(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordService)(nil).Hash), password)
}

// Verify mocks base method.
func (m *MockPasswordService) Verify(password, stored string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", password, stored)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockPasswordServiceMockRecorder) Verify(password, stored interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockPasswordService)(nil).Verify), password, stored)
}

// MocktokenPairIssuer is a mock of tokenPairIssuer interface.
type MocktokenPairIssuer struct {
	ctrl     *gomock.Controller
	recorder *MocktokenPairIssuerMockRecorder
}

// MocktokenPairIssuerMockRecorder is the mock recorder for MocktokenPairIssuer.
type MocktokenPairIssuerMockRecorder struct {
	mock *MocktokenPairIssuer
}

// NewMocktokenPairIssuer creates a new mock instance.
func NewMocktokenPairIssuer(ctrl *gomock.Controller) *MocktokenPairIssuer {
	mock := &MocktokenPairIssuer{ctrl: ctrl}
	mock.recorder = &MocktokenPairIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenPairIssuer) EXPECT() *MocktokenPairIssuerMockRecorder {
	return m.recorder
}

// IssueTokenPair mocks base method.
func (m *MocktokenPairIssuer) IssueTokenPair(ctx context.Context, u model0.User) (model.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokenPair", ctx, u)
	ret0, _ := ret[0].(model.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokenPair indicates an expected call of IssueTokenPair.
func (mr *MocktokenPairIssuerMockRecorder) IssueTokenPair(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenPair", reflect.TypeOf((*MocktokenPairIssuer)(nil).IssueTokenPair), ctx, u)
}
