// Code generated by MockGen. DO NOT EDIT.
// Source: internal/place/usecase/location_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	photon "cityhawk/backend/internal/integration/photon"
	model "cityhawk/backend/internal/place/model"
	repository "cityhawk/backend/internal/place/repository"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPhotonSearcher is a mock of PhotonSearcher interface.
type MockPhotonSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockPhotonSearcherMockRecorder
}

// MockPhotonSearcherMockRecorder is the mock recorder for MockPhotonSearcher.
type MockPhotonSearcherMockRecorder struct {
	mock *MockPhotonSearcher
}

// NewMockPhotonSearcher creates a new mock instance.
func NewMockPhotonSearcher(ctrl *gomock.Controller) *MockPhotonSearcher {
	mock := &MockPhotonSearcher{ctrl: ctrl}
	mock.recorder = &MockPhotonSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhotonSearcher) EXPECT() *MockPhotonSearcherMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockPhotonSearcher) Search(ctx context.Context, query string, limit int) ([]photon.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit)
	ret0, _ := ret[0].([]photon.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockPhotonSearcherMockRecorder) Search(ctx, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPhotonSearcher)(nil).Search), ctx, query, limit)
}

// MockPlaceLookupRepository is a mock of PlaceLookupRepository interface.
type MockPlaceLookupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlaceLookupRepositoryMockRecorder
}

// MockPlaceLookupRepositoryMockRecorder is the mock recorder for MockPlaceLookupRepository.
type MockPlaceLookupRepositoryMockRecorder struct {
	mock *MockPlaceLookupRepository
}

// NewMockPlaceLookupRepository creates a new mock instance.
func NewMockPlaceLookupRepository(ctrl *gomock.Controller) *MockPlaceLookupRepository {
	mock := &MockPlaceLookupRepository{ctrl: ctrl}
	mock.recorder = &MockPlaceLookupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaceLookupRepository) EXPECT() *MockPlaceLookupRepositoryMockRecorder {
	return m.recorder
}

// EnsurePlace mocks base method.
func (m *MockPlaceLookupRepository) EnsurePlace(ctx context.Context, input repository.PlaceLookupWriteInput) (model.PlaceResolved, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePlace", ctx, input)
	ret0, _ := ret[0].(model.PlaceResolved)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsurePlace indicates an expected call of EnsurePlace.
func (mr *MockPlaceLookupRepositoryMockRecorder) EnsurePlace(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePlace", reflect.TypeOf((*MockPlaceLookupRepository)(nil).EnsurePlace), ctx, input)
}
