DROP TRIGGER IF EXISTS set_notification_collection_updated_at ON notification_collection;
DROP TRIGGER IF EXISTS set_notification_invitation_updated_at ON notification_invitation;
DROP TRIGGER IF EXISTS set_notification_event_session_updated_at ON notification_event_session;
DROP TRIGGER IF EXISTS set_notification_event_updated_at ON notification_event;
DROP TRIGGER IF EXISTS set_notification_actor_updated_at ON notification_actor;
DROP TRIGGER IF EXISTS set_notification_updated_at ON notification;
DROP TRIGGER IF EXISTS set_share_link_collection_updated_at ON share_link_collection;
DROP TRIGGER IF EXISTS set_share_link_event_updated_at ON share_link_event;
DROP TRIGGER IF EXISTS set_event_invitation_session_updated_at ON event_invitation_session;
DROP TRIGGER IF EXISTS set_event_invitation_event_updated_at ON event_invitation_event;
DROP TRIGGER IF EXISTS set_share_link_updated_at ON share_link;
DROP TRIGGER IF EXISTS set_event_invitation_updated_at ON event_invitation;
DROP TRIGGER IF EXISTS set_user_follow_updated_at ON user_follow;
DROP TRIGGER IF EXISTS set_favorite_event_updated_at ON favorite_event;
DROP TRIGGER IF EXISTS set_collection_event_updated_at ON collection_event;
DROP TRIGGER IF EXISTS set_collection_image_updated_at ON collection_image;
DROP TRIGGER IF EXISTS set_collection_updated_at ON collection;
DROP TRIGGER IF EXISTS set_event_tag_updated_at ON event_tag;
DROP TRIGGER IF EXISTS set_event_category_updated_at ON event_category;
DROP TRIGGER IF EXISTS set_event_image_updated_at ON event_image;
DROP TRIGGER IF EXISTS set_event_session_updated_at ON event_session;
DROP TRIGGER IF EXISTS set_event_updated_at ON event;
DROP TRIGGER IF EXISTS set_tag_updated_at ON tag;
DROP TRIGGER IF EXISTS set_category_updated_at ON category;
DROP TRIGGER IF EXISTS set_place_updated_at ON place;
DROP TRIGGER IF EXISTS set_city_updated_at ON city;
DROP TRIGGER IF EXISTS set_user_account_updated_at ON user_account;

DROP TABLE IF EXISTS notification_collection CASCADE;
DROP TABLE IF EXISTS notification_invitation CASCADE;
DROP TABLE IF EXISTS notification_event_session CASCADE;
DROP TABLE IF EXISTS notification_event CASCADE;
DROP TABLE IF EXISTS notification_actor CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS share_link_collection CASCADE;
DROP TABLE IF EXISTS share_link_event CASCADE;
DROP TABLE IF EXISTS share_link CASCADE;
DROP TABLE IF EXISTS event_invitation_session CASCADE;
DROP TABLE IF EXISTS event_invitation_event CASCADE;
DROP TABLE IF EXISTS event_invitation CASCADE;
DROP TABLE IF EXISTS user_follow CASCADE;
DROP TABLE IF EXISTS favorite_event CASCADE;
DROP TABLE IF EXISTS collection_event CASCADE;
DROP TABLE IF EXISTS collection_image CASCADE;
DROP TABLE IF EXISTS collection CASCADE;
DROP TABLE IF EXISTS event_tag CASCADE;
DROP TABLE IF EXISTS event_category CASCADE;
DROP TABLE IF EXISTS event_image CASCADE;
DROP TABLE IF EXISTS event_session CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS place CASCADE;
DROP TABLE IF EXISTS refresh_session CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS city CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();
