// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cityhawk/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_ADMIN       UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_ADMIN":       2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_cityhawk_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_cityhawk_common_v1_common_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_cityhawk_common_v1_common_proto_rawDescGZIP(), []int{0}
}

type UserContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          UserRole               `protobuf:"varint,2,opt,name=role,proto3,enum=cityhawk.common.v1.UserRole" json:"role,omitempty"`
	Authenticated bool                   `protobuf:"varint,3,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_cityhawk_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *UserContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserContext) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *UserContext) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PageResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *IDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *BoolResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_cityhawk_common_v1_common_proto protoreflect.FileDescriptor

const file_cityhawk_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1fcityhawk/common/v1/common.proto\x12\x12cityhawk.common.v1\"~\n" +
	"\vUserContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1c.cityhawk.common.v1.UserRoleR\x04role\x12$\n" +
	"\rauthenticated\x18\x03 \x01(\bR\rauthenticated\";\n" +
	"\vPageRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"R\n" +
	"\fPageResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x1b\n" +
	"\tIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\fBoolResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*N\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02B,Z*cityhawk/backend/pkg/pb/common/v1;commonv1b\x06proto3"

var (
	file_cityhawk_common_v1_common_proto_rawDescOnce sync.Once
	file_cityhawk_common_v1_common_proto_rawDescData []byte
)

func file_cityhawk_common_v1_common_proto_rawDescGZIP() []byte {
	file_cityhawk_common_v1_common_proto_rawDescOnce.Do(func() {
		file_cityhawk_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cityhawk_common_v1_common_proto_rawDesc), len(file_cityhawk_common_v1_common_proto_rawDesc)))
	})
	return file_cityhawk_common_v1_common_proto_rawDescData
}

var file_cityhawk_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cityhawk_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cityhawk_common_v1_common_proto_goTypes = []any{
	(UserRole)(0),        // 0: cityhawk.common.v1.UserRole
	(*UserContext)(nil),  // 1: cityhawk.common.v1.UserContext
	(*PageRequest)(nil),  // 2: cityhawk.common.v1.PageRequest
	(*PageResponse)(nil), // 3: cityhawk.common.v1.PageResponse
	(*IDRequest)(nil),    // 4: cityhawk.common.v1.IDRequest
	(*BoolResponse)(nil), // 5: cityhawk.common.v1.BoolResponse
}
var file_cityhawk_common_v1_common_proto_depIdxs = []int32{
	0, // 0: cityhawk.common.v1.UserContext.role:type_name -> cityhawk.common.v1.UserRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cityhawk_common_v1_common_proto_init() }
func file_cityhawk_common_v1_common_proto_init() {
	if File_cityhawk_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cityhawk_common_v1_common_proto_rawDesc), len(file_cityhawk_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cityhawk_common_v1_common_proto_goTypes,
		DependencyIndexes: file_cityhawk_common_v1_common_proto_depIdxs,
		EnumInfos:         file_cityhawk_common_v1_common_proto_enumTypes,
		MessageInfos:      file_cityhawk_common_v1_common_proto_msgTypes,
	}.Build()
	File_cityhawk_common_v1_common_proto = out.File
	file_cityhawk_common_v1_common_proto_goTypes = nil
	file_cityhawk_common_v1_common_proto_depIdxs = nil
}
