package main

func newPlaceStore() *placeStore {
	s := &placeStore{
		byID: make(map[string]place),
	}

	for _, p := range []place{
		{
			ID:               "vdnh",
			Title:            "ВДНХ",
			Categories:       []string{"park"},
			LikeCount:        120,
			ShortDescription: "Большой парковый и выставочный комплекс для прогулок и активностей.",
			FullDescription:  "ВДНХ объединяет павильоны, парковые зоны и культурные площадки. Подходит для долгих прогулок, семейных выходных и посещения временных выставок.",
			Address:          "Москва, проспект Мира, 119",
			ImageURL:         "images/vdnh.jpg",
			WorkingHours:     "ежедневно, 10:00-22:00",
			PriceLevel:       "free",
		},
		{
			ID:               "garage",
			Title:            "Музей современного искусства Гараж",
			Categories:       []string{"museum", "photo"},
			LikeCount:        85,
			ShortDescription: "Современное искусство, выставки и лекции в Парке Горького.",
			FullDescription:  "Гараж проводит крупные выставки современных художников, образовательные программы и кинопоказы. Хороший вариант для культурного вечера и знакомства с актуальным искусством.",
			Address:          "Москва, ул. Крымский Вал, 9 стр. 32",
			ImageURL:         "images/garage.jpg",
			WorkingHours:     "вт-вс, 11:00-22:00",
			PriceLevel:       "medium",
		},
		{
			ID:               "zaryadye",
			Title:            "Парк Зарядье",
			Categories:       []string{"park", "photo"},
			LikeCount:        150,
			ShortDescription: "Центральный парк с панорамным мостом и видами на Кремль.",
			FullDescription:  "Зарядье расположен рядом с Красной площадью и известен парящим мостом, ландшафтными зонами и событийной программой. Подходит для короткой прогулки в центре города.",
			Address:          "Москва, ул. Варварка, 6",
			ImageURL:         "images/zaryadye.jpg",
			WorkingHours:     "ежедневно, 10:00-21:00",
			PriceLevel:       "free",
		},
		{
			ID:               "tretyakov",
			Title:            "Третьяковская галерея",
			Categories:       []string{"museum", "photo"},
			LikeCount:        132,
			ShortDescription: "Классическое русское искусство в главной национальной галерее.",
			FullDescription:  "Постоянная экспозиция Третьяковки включает знаковые работы русских художников разных эпох. Подходит для вдумчивого посещения и знакомства с историей искусства.",
			Address:          "Москва, Лаврушинский пер., 10",
			ImageURL:         "images/tretyakov.jpg",
			WorkingHours:     "вт-вс, 10:00-18:00",
			PriceLevel:       "medium",
		},
		{
			ID:               "gorky-park",
			Title:            "Парк Горького",
			Categories:       []string{"park"},
			LikeCount:        141,
			ShortDescription: "Большой городской парк для спорта, отдыха и событий.",
			FullDescription:  "Парк Горького объединяет прогулочные аллеи, веломаршруты, кафе и площадки для мероприятий. Удобный вариант для активного дня или спокойного вечера на набережной.",
			Address:          "Москва, Крымский Вал, 9",
			ImageURL:         "images/gorky-park.jpg",
			WorkingHours:     "ежедневно, 06:00-00:00",
			PriceLevel:       "free",
		},
		{
			ID:               "planetarium",
			Title:            "Московский планетарий",
			Categories:       []string{"museum", "family"},
			LikeCount:        97,
			ShortDescription: "Интерактивные залы и звездные программы для всей семьи.",
			FullDescription:  "Планетарий предлагает экскурсии, научные экспозиции и программы в Большом звездном зале. Хороший выбор для познавательного посещения с детьми и друзьями.",
			Address:          "Москва, ул. Садовая-Кудринская, 5 стр. 1",
			ImageURL:         "images/planetarium.jpg",
			WorkingHours:     "ежедневно, 10:00-21:00",
			PriceLevel:       "medium",
		},
		{
			ID:               "flacon",
			Title:            "Хлебозавод №9",
			Categories:       []string{"creative", "photo"},
			LikeCount:        74,
			ShortDescription: "Креативный кластер с маркетами, кофейнями и локальными брендами.",
			FullDescription:  "Пространство Хлебозавода объединяет магазины, выставки, поп-ап проекты и мероприятия на открытом воздухе. Подходит для прогулки по дизайн-локациям и встреч с друзьями.",
			Address:          "Москва, ул. Новодмитровская, 1",
			ImageURL:         "images/flacon.jpg",
			WorkingHours:     "ежедневно, 10:00-23:00",
			PriceLevel:       "medium",
		},
		{
			ID:               "tsaritsyno",
			Title:            "Музей-заповедник Царицыно",
			Categories:       []string{"park", "photo"},
			LikeCount:        110,
			ShortDescription: "Дворцово-парковый ансамбль с прудами и архитектурой XVIII века.",
			FullDescription:  "Царицыно сочетает большой пейзажный парк, дворцы и выставочные пространства. Место подходит для длительной прогулки, фотосессий и культурного отдыха.",
			Address:          "Москва, ул. Дольская, 1",
			ImageURL:         "images/tsaritsyno.jpg",
			WorkingHours:     "ежедневно, 06:00-00:00",
			PriceLevel:       "free",
		},
		{
			ID:               "pushkin-museum",
			Title:            "ГМИИ им. А. С. Пушкина",
			Categories:       []string{"museum", "photo"},
			LikeCount:        126,
			ShortDescription: "Крупная коллекция европейского искусства и временные выставки.",
			FullDescription:  "Пушкинский музей предлагает постоянные и временные экспозиции от античности до современности. Подходит для глубокого культурного маршрута в центре Москвы.",
			Address:          "Москва, ул. Волхонка, 12",
			ImageURL:         "images/pushkin-museum.jpg",
			WorkingHours:     "вт-вс, 11:00-20:00",
			PriceLevel:       "medium",
		},
		{
			ID:               "patriarch-pond",
			Title:            "Патриаршие пруды",
			Categories:       []string{"walk"},
			LikeCount:        89,
			ShortDescription: "Атмосферный район для неспешной прогулки и городских завтраков.",
			FullDescription:  "Патриаршие пруды известны уютными улицами, кафе и исторической застройкой. Локация подойдёт для спокойного маршрута по центру и встреч в выходные.",
			Address:          "Москва, Большой Патриарший пер., 7",
			ImageURL:         "images/patriarch-pond.jpg",
			WorkingHours:     "круглосуточно",
			PriceLevel:       "free",
		},
	} {
		s.byID[p.ID] = p
		s.order = append(s.order, p.ID)
	}

	return s
}
