// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cityhawk/profile/v1/profile.proto

package profilev1

import (
	v1 "cityhawk/backend/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileCity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CountryName   string                 `protobuf:"bytes,3,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileCity) Reset() {
	*x = ProfileCity{}
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileCity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileCity) ProtoMessage() {}

func (x *ProfileCity) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileCity.ProtoReflect.Descriptor instead.
func (*ProfileCity) Descriptor() ([]byte, []int) {
	return file_cityhawk_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileCity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileCity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileCity) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *ProfileCity) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	UserSurname   string                 `protobuf:"bytes,4,opt,name=user_surname,json=userSurname,proto3" json:"user_surname,omitempty"`
	Role          v1.UserRole            `protobuf:"varint,5,opt,name=role,proto3,enum=cityhawk.common.v1.UserRole" json:"role,omitempty"`
	Birthday      *string                `protobuf:"bytes,6,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	City          *ProfileCity           `protobuf:"bytes,8,opt,name=city,proto3,oneof" json:"city,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_cityhawk_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetUserSurname() string {
	if x != nil {
		return x.UserSurname
	}
	return ""
}

func (x *UserProfile) GetRole() v1.UserRole {
	if x != nil {
		return x.Role
	}
	return v1.UserRole(0)
}

func (x *UserProfile) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetCity() *ProfileCity {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *v1.UserContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetMeRequest) GetContext() *v1.UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type UpdateMeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *v1.UserContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Email          *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Username       *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	UserSurname    *string                `protobuf:"bytes,4,opt,name=user_surname,json=userSurname,proto3,oneof" json:"user_surname,omitempty"`
	Birthday       *string                `protobuf:"bytes,5,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	CityId         *string                `protobuf:"bytes,6,opt,name=city_id,json=cityId,proto3,oneof" json:"city_id,omitempty"`
	AvatarUrl      *string                `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	ClearBirthday  bool                   `protobuf:"varint,8,opt,name=clear_birthday,json=clearBirthday,proto3" json:"clear_birthday,omitempty"`
	ClearCityId    bool                   `protobuf:"varint,9,opt,name=clear_city_id,json=clearCityId,proto3" json:"clear_city_id,omitempty"`
	ClearAvatarUrl bool                   `protobuf:"varint,10,opt,name=clear_avatar_url,json=clearAvatarUrl,proto3" json:"clear_avatar_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMeRequest) Reset() {
	*x = UpdateMeRequest{}
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeRequest) ProtoMessage() {}

func (x *UpdateMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMeRequest) GetContext() *v1.UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateMeRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateMeRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateMeRequest) GetUserSurname() string {
	if x != nil && x.UserSurname != nil {
		return *x.UserSurname
	}
	return ""
}

func (x *UpdateMeRequest) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *UpdateMeRequest) GetCityId() string {
	if x != nil && x.CityId != nil {
		return *x.CityId
	}
	return ""
}

func (x *UpdateMeRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateMeRequest) GetClearBirthday() bool {
	if x != nil {
		return x.ClearBirthday
	}
	return false
}

func (x *UpdateMeRequest) GetClearCityId() bool {
	if x != nil {
		return x.ClearCityId
	}
	return false
}

func (x *UpdateMeRequest) GetClearAvatarUrl() bool {
	if x != nil {
		return x.ClearAvatarUrl
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewerContext *v1.UserContext        `protobuf:"bytes,2,opt,name=viewer_context,json=viewerContext,proto3,oneof" json:"viewer_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRequest) GetViewerContext() *v1.UserContext {
	if x != nil {
		return x.ViewerContext
	}
	return nil
}

var File_cityhawk_profile_v1_profile_proto protoreflect.FileDescriptor

const file_cityhawk_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"!cityhawk/profile/v1/profile.proto\x12\x13cityhawk.profile.v1\x1a\x1fcityhawk/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\vProfileCity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fcountry_name\x18\x03 \x01(\tR\vcountryName\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\"\xbf\x03\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12!\n" +
	"\fuser_surname\x18\x04 \x01(\tR\vuserSurname\x120\n" +
	"\x04role\x18\x05 \x01(\x0e2\x1c.cityhawk.common.v1.UserRoleR\x04role\x12\x1f\n" +
	"\bbirthday\x18\x06 \x01(\tH\x00R\bbirthday\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tH\x01R\tavatarUrl\x88\x01\x01\x129\n" +
	"\x04city\x18\b \x01(\v2 .cityhawk.profile.v1.ProfileCityH\x02R\x04city\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\v\n" +
	"\t_birthdayB\r\n" +
	"\v_avatar_urlB\a\n" +
	"\x05_city\"I\n" +
	"\fGetMeRequest\x129\n" +
	"\acontext\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\acontext\"\xd8\x03\n" +
	"\x0fUpdateMeRequest\x129\n" +
	"\acontext\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\acontext\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x01R\busername\x88\x01\x01\x12&\n" +
	"\fuser_surname\x18\x04 \x01(\tH\x02R\vuserSurname\x88\x01\x01\x12\x1f\n" +
	"\bbirthday\x18\x05 \x01(\tH\x03R\bbirthday\x88\x01\x01\x12\x1c\n" +
	"\acity_id\x18\x06 \x01(\tH\x04R\x06cityId\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tH\x05R\tavatarUrl\x88\x01\x01\x12%\n" +
	"\x0eclear_birthday\x18\b \x01(\bR\rclearBirthday\x12\"\n" +
	"\rclear_city_id\x18\t \x01(\bR\vclearCityId\x12(\n" +
	"\x10clear_avatar_url\x18\n" +
	" \x01(\bR\x0eclearAvatarUrlB\b\n" +
	"\x06_emailB\v\n" +
	"\t_usernameB\x0f\n" +
	"\r_user_surnameB\v\n" +
	"\t_birthdayB\n" +
	"\n" +
	"\b_city_idB\r\n" +
	"\v_avatar_url\"\x89\x01\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12K\n" +
	"\x0eviewer_context\x18\x02 \x01(\v2\x1f.cityhawk.common.v1.UserContextH\x00R\rviewerContext\x88\x01\x01B\x11\n" +
	"\x0f_viewer_context2\x8a\x02\n" +
	"\x0eProfileService\x12N\n" +
	"\x05GetMe\x12!.cityhawk.profile.v1.GetMeRequest\x1a .cityhawk.profile.v1.UserProfile\"\x00\x12T\n" +
	"\bUpdateMe\x12$.cityhawk.profile.v1.UpdateMeRequest\x1a .cityhawk.profile.v1.UserProfile\"\x00\x12R\n" +
	"\aGetUser\x12#.cityhawk.profile.v1.GetUserRequest\x1a .cityhawk.profile.v1.UserProfile\"\x00B.Z,cityhawk/backend/pkg/pb/profile/v1;profilev1b\x06proto3"

var (
	file_cityhawk_profile_v1_profile_proto_rawDescOnce sync.Once
	file_cityhawk_profile_v1_profile_proto_rawDescData []byte
)

func file_cityhawk_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_cityhawk_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_cityhawk_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cityhawk_profile_v1_profile_proto_rawDesc), len(file_cityhawk_profile_v1_profile_proto_rawDesc)))
	})
	return file_cityhawk_profile_v1_profile_proto_rawDescData
}

var file_cityhawk_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cityhawk_profile_v1_profile_proto_goTypes = []any{
	(*ProfileCity)(nil),           // 0: cityhawk.profile.v1.ProfileCity
	(*UserProfile)(nil),           // 1: cityhawk.profile.v1.UserProfile
	(*GetMeRequest)(nil),          // 2: cityhawk.profile.v1.GetMeRequest
	(*UpdateMeRequest)(nil),       // 3: cityhawk.profile.v1.UpdateMeRequest
	(*GetUserRequest)(nil),        // 4: cityhawk.profile.v1.GetUserRequest
	(v1.UserRole)(0),              // 5: cityhawk.common.v1.UserRole
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*v1.UserContext)(nil),        // 7: cityhawk.common.v1.UserContext
}
var file_cityhawk_profile_v1_profile_proto_depIdxs = []int32{
	5,  // 0: cityhawk.profile.v1.UserProfile.role:type_name -> cityhawk.common.v1.UserRole
	0,  // 1: cityhawk.profile.v1.UserProfile.city:type_name -> cityhawk.profile.v1.ProfileCity
	6,  // 2: cityhawk.profile.v1.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: cityhawk.profile.v1.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 4: cityhawk.profile.v1.GetMeRequest.context:type_name -> cityhawk.common.v1.UserContext
	7,  // 5: cityhawk.profile.v1.UpdateMeRequest.context:type_name -> cityhawk.common.v1.UserContext
	7,  // 6: cityhawk.profile.v1.GetUserRequest.viewer_context:type_name -> cityhawk.common.v1.UserContext
	2,  // 7: cityhawk.profile.v1.ProfileService.GetMe:input_type -> cityhawk.profile.v1.GetMeRequest
	3,  // 8: cityhawk.profile.v1.ProfileService.UpdateMe:input_type -> cityhawk.profile.v1.UpdateMeRequest
	4,  // 9: cityhawk.profile.v1.ProfileService.GetUser:input_type -> cityhawk.profile.v1.GetUserRequest
	1,  // 10: cityhawk.profile.v1.ProfileService.GetMe:output_type -> cityhawk.profile.v1.UserProfile
	1,  // 11: cityhawk.profile.v1.ProfileService.UpdateMe:output_type -> cityhawk.profile.v1.UserProfile
	1,  // 12: cityhawk.profile.v1.ProfileService.GetUser:output_type -> cityhawk.profile.v1.UserProfile
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cityhawk_profile_v1_profile_proto_init() }
func file_cityhawk_profile_v1_profile_proto_init() {
	if File_cityhawk_profile_v1_profile_proto != nil {
		return
	}
	file_cityhawk_profile_v1_profile_proto_msgTypes[1].OneofWrappers = []any{}
	file_cityhawk_profile_v1_profile_proto_msgTypes[3].OneofWrappers = []any{}
	file_cityhawk_profile_v1_profile_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cityhawk_profile_v1_profile_proto_rawDesc), len(file_cityhawk_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cityhawk_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_cityhawk_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_cityhawk_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_cityhawk_profile_v1_profile_proto = out.File
	file_cityhawk_profile_v1_profile_proto_goTypes = nil
	file_cityhawk_profile_v1_profile_proto_depIdxs = nil
}
