// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: cityhawk/events/v1/events.proto

package eventsv1

import (
	v1 "cityhawk/backend/pkg/pb/common/v1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventsService_GetHome_FullMethodName                 = "/cityhawk.events.v1.EventsService/GetHome"
	EventsService_ListEvents_FullMethodName              = "/cityhawk.events.v1.EventsService/ListEvents"
	EventsService_SearchEventsNearby_FullMethodName      = "/cityhawk.events.v1.EventsService/SearchEventsNearby"
	EventsService_GetEvent_FullMethodName                = "/cityhawk.events.v1.EventsService/GetEvent"
	EventsService_CreateEvent_FullMethodName             = "/cityhawk.events.v1.EventsService/CreateEvent"
	EventsService_UpdateEvent_FullMethodName             = "/cityhawk.events.v1.EventsService/UpdateEvent"
	EventsService_DeleteEvent_FullMethodName             = "/cityhawk.events.v1.EventsService/DeleteEvent"
	EventsService_ListCategories_FullMethodName          = "/cityhawk.events.v1.EventsService/ListCategories"
	EventsService_ListTags_FullMethodName                = "/cityhawk.events.v1.EventsService/ListTags"
	EventsService_ListCities_FullMethodName              = "/cityhawk.events.v1.EventsService/ListCities"
	EventsService_ListCollections_FullMethodName         = "/cityhawk.events.v1.EventsService/ListCollections"
	EventsService_GetCollection_FullMethodName           = "/cityhawk.events.v1.EventsService/GetCollection"
	EventsService_SearchSuggestions_FullMethodName       = "/cityhawk.events.v1.EventsService/SearchSuggestions"
	EventsService_SuggestPlaces_FullMethodName           = "/cityhawk.events.v1.EventsService/SuggestPlaces"
	EventsService_ResolvePlace_FullMethodName            = "/cityhawk.events.v1.EventsService/ResolvePlace"
	EventsService_CreatePlace_FullMethodName             = "/cityhawk.events.v1.EventsService/CreatePlace"
	EventsService_UpdatePlace_FullMethodName             = "/cityhawk.events.v1.EventsService/UpdatePlace"
	EventsService_GenerateCollectionDraft_FullMethodName = "/cityhawk.events.v1.EventsService/GenerateCollectionDraft"
)

// EventsServiceClient is the client API for EventsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventsServiceClient interface {
	GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*HomeResponse, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	SearchEventsNearby(ctx context.Context, in *SearchEventsNearbyRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventDetails, error)
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*EventIDResponse, error)
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*EventIDResponse, error)
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*v1.BoolResponse, error)
	ListCategories(ctx context.Context, in *ListTaxonomyRequest, opts ...grpc.CallOption) (*ListTaxonomyResponse, error)
	ListTags(ctx context.Context, in *ListTaxonomyRequest, opts ...grpc.CallOption) (*ListTaxonomyResponse, error)
	ListCities(ctx context.Context, in *ListCitiesRequest, opts ...grpc.CallOption) (*ListCitiesResponse, error)
	ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	GetCollection(ctx context.Context, in *GetCollectionRequest, opts ...grpc.CallOption) (*CollectionDetails, error)
	SearchSuggestions(ctx context.Context, in *SearchSuggestionsRequest, opts ...grpc.CallOption) (*SearchSuggestionsResponse, error)
	SuggestPlaces(ctx context.Context, in *SuggestPlacesRequest, opts ...grpc.CallOption) (*SuggestPlacesResponse, error)
	ResolvePlace(ctx context.Context, in *ResolvePlaceRequest, opts ...grpc.CallOption) (*Place, error)
	CreatePlace(ctx context.Context, in *CreatePlaceRequest, opts ...grpc.CallOption) (*Place, error)
	UpdatePlace(ctx context.Context, in *UpdatePlaceRequest, opts ...grpc.CallOption) (*Place, error)
	GenerateCollectionDraft(ctx context.Context, in *GenerateCollectionDraftRequest, opts ...grpc.CallOption) (*GenerateCollectionDraftResponse, error)
}

type eventsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsServiceClient(cc grpc.ClientConnInterface) EventsServiceClient {
	return &eventsServiceClient{cc}
}

func (c *eventsServiceClient) GetHome(ctx context.Context, in *GetHomeRequest, opts ...grpc.CallOption) (*HomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeResponse)
	err := c.cc.Invoke(ctx, EventsService_GetHome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventsService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) SearchEventsNearby(ctx context.Context, in *SearchEventsNearbyRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, EventsService_SearchEventsNearby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*EventDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventDetails)
	err := c.cc.Invoke(ctx, EventsService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*EventIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventIDResponse)
	err := c.cc.Invoke(ctx, EventsService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*EventIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventIDResponse)
	err := c.cc.Invoke(ctx, EventsService_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*v1.BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.BoolResponse)
	err := c.cc.Invoke(ctx, EventsService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ListCategories(ctx context.Context, in *ListTaxonomyRequest, opts ...grpc.CallOption) (*ListTaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaxonomyResponse)
	err := c.cc.Invoke(ctx, EventsService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ListTags(ctx context.Context, in *ListTaxonomyRequest, opts ...grpc.CallOption) (*ListTaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaxonomyResponse)
	err := c.cc.Invoke(ctx, EventsService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ListCities(ctx context.Context, in *ListCitiesRequest, opts ...grpc.CallOption) (*ListCitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCitiesResponse)
	err := c.cc.Invoke(ctx, EventsService_ListCities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, EventsService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GetCollection(ctx context.Context, in *GetCollectionRequest, opts ...grpc.CallOption) (*CollectionDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectionDetails)
	err := c.cc.Invoke(ctx, EventsService_GetCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) SearchSuggestions(ctx context.Context, in *SearchSuggestionsRequest, opts ...grpc.CallOption) (*SearchSuggestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSuggestionsResponse)
	err := c.cc.Invoke(ctx, EventsService_SearchSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) SuggestPlaces(ctx context.Context, in *SuggestPlacesRequest, opts ...grpc.CallOption) (*SuggestPlacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestPlacesResponse)
	err := c.cc.Invoke(ctx, EventsService_SuggestPlaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) ResolvePlace(ctx context.Context, in *ResolvePlaceRequest, opts ...grpc.CallOption) (*Place, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Place)
	err := c.cc.Invoke(ctx, EventsService_ResolvePlace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) CreatePlace(ctx context.Context, in *CreatePlaceRequest, opts ...grpc.CallOption) (*Place, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Place)
	err := c.cc.Invoke(ctx, EventsService_CreatePlace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) UpdatePlace(ctx context.Context, in *UpdatePlaceRequest, opts ...grpc.CallOption) (*Place, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Place)
	err := c.cc.Invoke(ctx, EventsService_UpdatePlace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) GenerateCollectionDraft(ctx context.Context, in *GenerateCollectionDraftRequest, opts ...grpc.CallOption) (*GenerateCollectionDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCollectionDraftResponse)
	err := c.cc.Invoke(ctx, EventsService_GenerateCollectionDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServiceServer is the server API for EventsService service.
// All implementations must embed UnimplementedEventsServiceServer
// for forward compatibility.
type EventsServiceServer interface {
	GetHome(context.Context, *GetHomeRequest) (*HomeResponse, error)
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	SearchEventsNearby(context.Context, *SearchEventsNearbyRequest) (*ListEventsResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*EventDetails, error)
	CreateEvent(context.Context, *CreateEventRequest) (*EventIDResponse, error)
	UpdateEvent(context.Context, *UpdateEventRequest) (*EventIDResponse, error)
	DeleteEvent(context.Context, *DeleteEventRequest) (*v1.BoolResponse, error)
	ListCategories(context.Context, *ListTaxonomyRequest) (*ListTaxonomyResponse, error)
	ListTags(context.Context, *ListTaxonomyRequest) (*ListTaxonomyResponse, error)
	ListCities(context.Context, *ListCitiesRequest) (*ListCitiesResponse, error)
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	GetCollection(context.Context, *GetCollectionRequest) (*CollectionDetails, error)
	SearchSuggestions(context.Context, *SearchSuggestionsRequest) (*SearchSuggestionsResponse, error)
	SuggestPlaces(context.Context, *SuggestPlacesRequest) (*SuggestPlacesResponse, error)
	ResolvePlace(context.Context, *ResolvePlaceRequest) (*Place, error)
	CreatePlace(context.Context, *CreatePlaceRequest) (*Place, error)
	UpdatePlace(context.Context, *UpdatePlaceRequest) (*Place, error)
	GenerateCollectionDraft(context.Context, *GenerateCollectionDraftRequest) (*GenerateCollectionDraftResponse, error)
	mustEmbedUnimplementedEventsServiceServer()
}

// UnimplementedEventsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventsServiceServer struct{}

func (UnimplementedEventsServiceServer) GetHome(context.Context, *GetHomeRequest) (*HomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHome not implemented")
}
func (UnimplementedEventsServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedEventsServiceServer) SearchEventsNearby(context.Context, *SearchEventsNearbyRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEventsNearby not implemented")
}
func (UnimplementedEventsServiceServer) GetEvent(context.Context, *GetEventRequest) (*EventDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedEventsServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*EventIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedEventsServiceServer) UpdateEvent(context.Context, *UpdateEventRequest) (*EventIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedEventsServiceServer) DeleteEvent(context.Context, *DeleteEventRequest) (*v1.BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedEventsServiceServer) ListCategories(context.Context, *ListTaxonomyRequest) (*ListTaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedEventsServiceServer) ListTags(context.Context, *ListTaxonomyRequest) (*ListTaxonomyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedEventsServiceServer) ListCities(context.Context, *ListCitiesRequest) (*ListCitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCities not implemented")
}
func (UnimplementedEventsServiceServer) ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedEventsServiceServer) GetCollection(context.Context, *GetCollectionRequest) (*CollectionDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollection not implemented")
}
func (UnimplementedEventsServiceServer) SearchSuggestions(context.Context, *SearchSuggestionsRequest) (*SearchSuggestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSuggestions not implemented")
}
func (UnimplementedEventsServiceServer) SuggestPlaces(context.Context, *SuggestPlacesRequest) (*SuggestPlacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestPlaces not implemented")
}
func (UnimplementedEventsServiceServer) ResolvePlace(context.Context, *ResolvePlaceRequest) (*Place, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolvePlace not implemented")
}
func (UnimplementedEventsServiceServer) CreatePlace(context.Context, *CreatePlaceRequest) (*Place, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlace not implemented")
}
func (UnimplementedEventsServiceServer) UpdatePlace(context.Context, *UpdatePlaceRequest) (*Place, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlace not implemented")
}
func (UnimplementedEventsServiceServer) GenerateCollectionDraft(context.Context, *GenerateCollectionDraftRequest) (*GenerateCollectionDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCollectionDraft not implemented")
}
func (UnimplementedEventsServiceServer) mustEmbedUnimplementedEventsServiceServer() {}
func (UnimplementedEventsServiceServer) testEmbeddedByValue()                       {}

// UnsafeEventsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsServiceServer will
// result in compilation errors.
type UnsafeEventsServiceServer interface {
	mustEmbedUnimplementedEventsServiceServer()
}

func RegisterEventsServiceServer(s grpc.ServiceRegistrar, srv EventsServiceServer) {
	// If the following call panics, it indicates UnimplementedEventsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventsService_ServiceDesc, srv)
}

func _EventsService_GetHome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetHome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetHome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetHome(ctx, req.(*GetHomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_SearchEventsNearby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsNearbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).SearchEventsNearby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_SearchEventsNearby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).SearchEventsNearby(ctx, req.(*SearchEventsNearbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ListCategories(ctx, req.(*ListTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ListTags(ctx, req.(*ListTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ListCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ListCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ListCities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ListCities(ctx, req.(*ListCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetCollection(ctx, req.(*GetCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_SearchSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).SearchSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_SearchSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).SearchSuggestions(ctx, req.(*SearchSuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_SuggestPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestPlacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).SuggestPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_SuggestPlaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).SuggestPlaces(ctx, req.(*SuggestPlacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_ResolvePlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).ResolvePlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_ResolvePlace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).ResolvePlace(ctx, req.(*ResolvePlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_CreatePlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).CreatePlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_CreatePlace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).CreatePlace(ctx, req.(*CreatePlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_UpdatePlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).UpdatePlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_UpdatePlace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).UpdatePlace(ctx, req.(*UpdatePlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_GenerateCollectionDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCollectionDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GenerateCollectionDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GenerateCollectionDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GenerateCollectionDraft(ctx, req.(*GenerateCollectionDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventsService_ServiceDesc is the grpc.ServiceDesc for EventsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cityhawk.events.v1.EventsService",
	HandlerType: (*EventsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHome",
			Handler:    _EventsService_GetHome_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _EventsService_ListEvents_Handler,
		},
		{
			MethodName: "SearchEventsNearby",
			Handler:    _EventsService_SearchEventsNearby_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventsService_GetEvent_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _EventsService_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventsService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventsService_DeleteEvent_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _EventsService_ListCategories_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _EventsService_ListTags_Handler,
		},
		{
			MethodName: "ListCities",
			Handler:    _EventsService_ListCities_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _EventsService_ListCollections_Handler,
		},
		{
			MethodName: "GetCollection",
			Handler:    _EventsService_GetCollection_Handler,
		},
		{
			MethodName: "SearchSuggestions",
			Handler:    _EventsService_SearchSuggestions_Handler,
		},
		{
			MethodName: "SuggestPlaces",
			Handler:    _EventsService_SuggestPlaces_Handler,
		},
		{
			MethodName: "ResolvePlace",
			Handler:    _EventsService_ResolvePlace_Handler,
		},
		{
			MethodName: "CreatePlace",
			Handler:    _EventsService_CreatePlace_Handler,
		},
		{
			MethodName: "UpdatePlace",
			Handler:    _EventsService_UpdatePlace_Handler,
		},
		{
			MethodName: "GenerateCollectionDraft",
			Handler:    _EventsService_GenerateCollectionDraft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cityhawk/events/v1/events.proto",
}
