// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeCityhawkBackendInternalOrganizerDeliveryHttp(in *jlexer.Lexer, out *updateApplicationStatusRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reviewComment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReviewComment = string(in.String())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeCityhawkBackendInternalOrganizerDeliveryHttp(out *jwriter.Writer, in updateApplicationStatusRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"reviewComment\":"
		out.RawString(prefix)
		out.String(string(in.ReviewComment))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v updateApplicationStatusRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeCityhawkBackendInternalOrganizerDeliveryHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v updateApplicationStatusRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeCityhawkBackendInternalOrganizerDeliveryHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *updateApplicationStatusRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeCityhawkBackendInternalOrganizerDeliveryHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *updateApplicationStatusRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeCityhawkBackendInternalOrganizerDeliveryHttp(l, v)
}
func easyjson3c9d2b01DecodeCityhawkBackendInternalOrganizerDeliveryHttp1(in *jlexer.Lexer, out *createApplicationRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Phone = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
			} else {
				out.City = string(in.String())
			}
		case "projectName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProjectName = string(in.String())
			}
		case "categories":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Categories = string(in.String())
			}
		case "links":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Links = string(in.String())
			}
		case "about":
			if in.IsNull() {
				in.Skip()
			} else {
				out.About = string(in.String())
			}
		case "consent":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Consent = bool(in.Bool())
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeCityhawkBackendInternalOrganizerDeliveryHttp1(out *jwriter.Writer, in createApplicationRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"projectName\":"
		out.RawString(prefix)
		out.String(string(in.ProjectName))
	}
	{
		const prefix string = ",\"categories\":"
		out.RawString(prefix)
		out.String(string(in.Categories))
	}
	{
		const prefix string = ",\"links\":"
		out.RawString(prefix)
		out.String(string(in.Links))
	}
	{
		const prefix string = ",\"about\":"
		out.RawString(prefix)
		out.String(string(in.About))
	}
	{
		const prefix string = ",\"consent\":"
		out.RawString(prefix)
		out.Bool(bool(in.Consent))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createApplicationRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeCityhawkBackendInternalOrganizerDeliveryHttp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createApplicationRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeCityhawkBackendInternalOrganizerDeliveryHttp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createApplicationRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeCityhawkBackendInternalOrganizerDeliveryHttp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createApplicationRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeCityhawkBackendInternalOrganizerDeliveryHttp1(l, v)
}
