// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cityhawk/social/v1/social.proto

package socialv1

import (
	v1 "cityhawk/backend/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFavoriteRequest) Reset() {
	*x = AddFavoriteRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFavoriteRequest) ProtoMessage() {}

func (x *AddFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{0}
}

func (x *AddFavoriteRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AddFavoriteRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type RemoveFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFavoriteRequest) Reset() {
	*x = RemoveFavoriteRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFavoriteRequest) ProtoMessage() {}

func (x *RemoveFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveFavoriteRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *RemoveFavoriteRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListFavoriteEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteEventsRequest) Reset() {
	*x = ListFavoriteEventsRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteEventsRequest) ProtoMessage() {}

func (x *ListFavoriteEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteEventsRequest.ProtoReflect.Descriptor instead.
func (*ListFavoriteEventsRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{2}
}

func (x *ListFavoriteEventsRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ListFavoriteEventsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListFavoriteEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FavoriteEvent       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFavoriteEventsResponse) Reset() {
	*x = ListFavoriteEventsResponse{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFavoriteEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFavoriteEventsResponse) ProtoMessage() {}

func (x *ListFavoriteEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFavoriteEventsResponse.ProtoReflect.Descriptor instead.
func (*ListFavoriteEventsResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{3}
}

func (x *ListFavoriteEventsResponse) GetItems() []*FavoriteEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFavoriteEventsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type FavoriteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteEvent) Reset() {
	*x = FavoriteEvent{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteEvent) ProtoMessage() {}

func (x *FavoriteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteEvent.ProtoReflect.Descriptor instead.
func (*FavoriteEvent) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{4}
}

func (x *FavoriteEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FavoriteEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type IsFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteRequest) Reset() {
	*x = IsFavoriteRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteRequest) ProtoMessage() {}

func (x *IsFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteRequest.ProtoReflect.Descriptor instead.
func (*IsFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{5}
}

func (x *IsFavoriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsFavoriteRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type IsFavoriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFavorite    bool                   `protobuf:"varint,1,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFavoriteResponse) Reset() {
	*x = IsFavoriteResponse{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFavoriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFavoriteResponse) ProtoMessage() {}

func (x *IsFavoriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFavoriteResponse.ProtoReflect.Descriptor instead.
func (*IsFavoriteResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{6}
}

func (x *IsFavoriteResponse) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type FollowUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Actor          *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	FollowedUserId string                 `protobuf:"bytes,2,opt,name=followed_user_id,json=followedUserId,proto3" json:"followed_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{7}
}

func (x *FollowUserRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *FollowUserRequest) GetFollowedUserId() string {
	if x != nil {
		return x.FollowedUserId
	}
	return ""
}

type UnfollowUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Actor          *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	FollowedUserId string                 `protobuf:"bytes,2,opt,name=followed_user_id,json=followedUserId,proto3" json:"followed_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{8}
}

func (x *UnfollowUserRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *UnfollowUserRequest) GetFollowedUserId() string {
	if x != nil {
		return x.FollowedUserId
	}
	return ""
}

type ListFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewerContext *v1.UserContext        `protobuf:"bytes,2,opt,name=viewer_context,json=viewerContext,proto3,oneof" json:"viewer_context,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowersRequest) Reset() {
	*x = ListFollowersRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowersRequest) ProtoMessage() {}

func (x *ListFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowersRequest.ProtoReflect.Descriptor instead.
func (*ListFollowersRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{9}
}

func (x *ListFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFollowersRequest) GetViewerContext() *v1.UserContext {
	if x != nil {
		return x.ViewerContext
	}
	return nil
}

func (x *ListFollowersRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewerContext *v1.UserContext        `protobuf:"bytes,2,opt,name=viewer_context,json=viewerContext,proto3,oneof" json:"viewer_context,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFollowingRequest) Reset() {
	*x = ListFollowingRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFollowingRequest) ProtoMessage() {}

func (x *ListFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFollowingRequest.ProtoReflect.Descriptor instead.
func (*ListFollowingRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{10}
}

func (x *ListFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFollowingRequest) GetViewerContext() *v1.UserContext {
	if x != nil {
		return x.ViewerContext
	}
	return nil
}

func (x *ListFollowingRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserFollow          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetItems() []*UserFollow {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListUsersResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type UserFollow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,2,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFollow) Reset() {
	*x = UserFollow{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollow) ProtoMessage() {}

func (x *UserFollow) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollow.ProtoReflect.Descriptor instead.
func (*UserFollow) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{12}
}

func (x *UserFollow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFollow) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *UserFollow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type IsFollowingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FollowerUserId string                 `protobuf:"bytes,1,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"`
	FollowedUserId string                 `protobuf:"bytes,2,opt,name=followed_user_id,json=followedUserId,proto3" json:"followed_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{13}
}

func (x *IsFollowingRequest) GetFollowerUserId() string {
	if x != nil {
		return x.FollowerUserId
	}
	return ""
}

func (x *IsFollowingRequest) GetFollowedUserId() string {
	if x != nil {
		return x.FollowedUserId
	}
	return ""
}

type IsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResponse) Reset() {
	*x = IsFollowingResponse{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResponse) ProtoMessage() {}

func (x *IsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResponse.ProtoReflect.Descriptor instead.
func (*IsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{14}
}

func (x *IsFollowingResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type GetSocialFlagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewerContext *v1.UserContext        `protobuf:"bytes,1,opt,name=viewer_context,json=viewerContext,proto3,oneof" json:"viewer_context,omitempty"`
	EventIds      []string               `protobuf:"bytes,2,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	AuthorUserIds []string               `protobuf:"bytes,3,rep,name=author_user_ids,json=authorUserIds,proto3" json:"author_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSocialFlagsRequest) Reset() {
	*x = GetSocialFlagsRequest{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSocialFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSocialFlagsRequest) ProtoMessage() {}

func (x *GetSocialFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSocialFlagsRequest.ProtoReflect.Descriptor instead.
func (*GetSocialFlagsRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{15}
}

func (x *GetSocialFlagsRequest) GetViewerContext() *v1.UserContext {
	if x != nil {
		return x.ViewerContext
	}
	return nil
}

func (x *GetSocialFlagsRequest) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *GetSocialFlagsRequest) GetAuthorUserIds() []string {
	if x != nil {
		return x.AuthorUserIds
	}
	return nil
}

type EventFavoriteFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,2,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFavoriteFlag) Reset() {
	*x = EventFavoriteFlag{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFavoriteFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFavoriteFlag) ProtoMessage() {}

func (x *EventFavoriteFlag) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFavoriteFlag.ProtoReflect.Descriptor instead.
func (*EventFavoriteFlag) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{16}
}

func (x *EventFavoriteFlag) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventFavoriteFlag) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *EventFavoriteFlag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserFollowingFlag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsFollowing   bool                   `protobuf:"varint,2,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFollowingFlag) Reset() {
	*x = UserFollowingFlag{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollowingFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollowingFlag) ProtoMessage() {}

func (x *UserFollowingFlag) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollowingFlag.ProtoReflect.Descriptor instead.
func (*UserFollowingFlag) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{17}
}

func (x *UserFollowingFlag) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFollowingFlag) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

func (x *UserFollowingFlag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SocialFlagsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FavoriteEvents []*EventFavoriteFlag   `protobuf:"bytes,1,rep,name=favorite_events,json=favoriteEvents,proto3" json:"favorite_events,omitempty"`
	FollowingUsers []*UserFollowingFlag   `protobuf:"bytes,2,rep,name=following_users,json=followingUsers,proto3" json:"following_users,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SocialFlagsResponse) Reset() {
	*x = SocialFlagsResponse{}
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialFlagsResponse) ProtoMessage() {}

func (x *SocialFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_social_v1_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialFlagsResponse.ProtoReflect.Descriptor instead.
func (*SocialFlagsResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_social_v1_social_proto_rawDescGZIP(), []int{18}
}

func (x *SocialFlagsResponse) GetFavoriteEvents() []*EventFavoriteFlag {
	if x != nil {
		return x.FavoriteEvents
	}
	return nil
}

func (x *SocialFlagsResponse) GetFollowingUsers() []*UserFollowingFlag {
	if x != nil {
		return x.FollowingUsers
	}
	return nil
}

var File_cityhawk_social_v1_social_proto protoreflect.FileDescriptor

const file_cityhawk_social_v1_social_proto_rawDesc = "" +
	"\n" +
	"\x1fcityhawk/social/v1/social.proto\x12\x12cityhawk.social.v1\x1a\x1fcityhawk/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"f\n" +
	"\x12AddFavoriteRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"i\n" +
	"\x15RemoveFavoriteRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"\x87\x01\n" +
	"\x19ListFavoriteEventsRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x123\n" +
	"\x04page\x18\x02 \x01(\v2\x1f.cityhawk.common.v1.PageRequestR\x04page\"\x8b\x01\n" +
	"\x1aListFavoriteEventsResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.cityhawk.social.v1.FavoriteEventR\x05items\x124\n" +
	"\x04page\x18\x02 \x01(\v2 .cityhawk.common.v1.PageResponseR\x04page\"e\n" +
	"\rFavoriteEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"G\n" +
	"\x11IsFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"5\n" +
	"\x12IsFavoriteResponse\x12\x1f\n" +
	"\vis_favorite\x18\x01 \x01(\bR\n" +
	"isFavorite\"t\n" +
	"\x11FollowUserRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12(\n" +
	"\x10followed_user_id\x18\x02 \x01(\tR\x0efollowedUserId\"v\n" +
	"\x13UnfollowUserRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12(\n" +
	"\x10followed_user_id\x18\x02 \x01(\tR\x0efollowedUserId\"\xc4\x01\n" +
	"\x14ListFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12K\n" +
	"\x0eviewer_context\x18\x02 \x01(\v2\x1f.cityhawk.common.v1.UserContextH\x00R\rviewerContext\x88\x01\x01\x123\n" +
	"\x04page\x18\x03 \x01(\v2\x1f.cityhawk.common.v1.PageRequestR\x04pageB\x11\n" +
	"\x0f_viewer_context\"\xc4\x01\n" +
	"\x14ListFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12K\n" +
	"\x0eviewer_context\x18\x02 \x01(\v2\x1f.cityhawk.common.v1.UserContextH\x00R\rviewerContext\x88\x01\x01\x123\n" +
	"\x04page\x18\x03 \x01(\v2\x1f.cityhawk.common.v1.PageRequestR\x04pageB\x11\n" +
	"\x0f_viewer_context\"\x7f\n" +
	"\x11ListUsersResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.cityhawk.social.v1.UserFollowR\x05items\x124\n" +
	"\x04page\x18\x02 \x01(\v2 .cityhawk.common.v1.PageResponseR\x04page\"\x83\x01\n" +
	"\n" +
	"UserFollow\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fis_following\x18\x02 \x01(\bR\visFollowing\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"h\n" +
	"\x12IsFollowingRequest\x12(\n" +
	"\x10follower_user_id\x18\x01 \x01(\tR\x0efollowerUserId\x12(\n" +
	"\x10followed_user_id\x18\x02 \x01(\tR\x0efollowedUserId\"8\n" +
	"\x13IsFollowingResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\"\xbc\x01\n" +
	"\x15GetSocialFlagsRequest\x12K\n" +
	"\x0eviewer_context\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextH\x00R\rviewerContext\x88\x01\x01\x12\x1b\n" +
	"\tevent_ids\x18\x02 \x03(\tR\beventIds\x12&\n" +
	"\x0fauthor_user_ids\x18\x03 \x03(\tR\rauthorUserIdsB\x11\n" +
	"\x0f_viewer_context\"\x8a\x01\n" +
	"\x11EventFavoriteFlag\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vis_favorite\x18\x02 \x01(\bR\n" +
	"isFavorite\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x01\n" +
	"\x11UserFollowingFlag\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fis_following\x18\x02 \x01(\bR\visFollowing\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb5\x01\n" +
	"\x13SocialFlagsResponse\x12N\n" +
	"\x0ffavorite_events\x18\x01 \x03(\v2%.cityhawk.social.v1.EventFavoriteFlagR\x0efavoriteEvents\x12N\n" +
	"\x0ffollowing_users\x18\x02 \x03(\v2%.cityhawk.social.v1.UserFollowingFlagR\x0efollowingUsers2\xe9\a\n" +
	"\rSocialService\x12Y\n" +
	"\vAddFavorite\x12&.cityhawk.social.v1.AddFavoriteRequest\x1a .cityhawk.common.v1.BoolResponse\"\x00\x12_\n" +
	"\x0eRemoveFavorite\x12).cityhawk.social.v1.RemoveFavoriteRequest\x1a .cityhawk.common.v1.BoolResponse\"\x00\x12u\n" +
	"\x12ListFavoriteEvents\x12-.cityhawk.social.v1.ListFavoriteEventsRequest\x1a..cityhawk.social.v1.ListFavoriteEventsResponse\"\x00\x12]\n" +
	"\n" +
	"IsFavorite\x12%.cityhawk.social.v1.IsFavoriteRequest\x1a&.cityhawk.social.v1.IsFavoriteResponse\"\x00\x12W\n" +
	"\n" +
	"FollowUser\x12%.cityhawk.social.v1.FollowUserRequest\x1a .cityhawk.common.v1.BoolResponse\"\x00\x12[\n" +
	"\fUnfollowUser\x12'.cityhawk.social.v1.UnfollowUserRequest\x1a .cityhawk.common.v1.BoolResponse\"\x00\x12b\n" +
	"\rListFollowers\x12(.cityhawk.social.v1.ListFollowersRequest\x1a%.cityhawk.social.v1.ListUsersResponse\"\x00\x12b\n" +
	"\rListFollowing\x12(.cityhawk.social.v1.ListFollowingRequest\x1a%.cityhawk.social.v1.ListUsersResponse\"\x00\x12`\n" +
	"\vIsFollowing\x12&.cityhawk.social.v1.IsFollowingRequest\x1a'.cityhawk.social.v1.IsFollowingResponse\"\x00\x12f\n" +
	"\x0eGetSocialFlags\x12).cityhawk.social.v1.GetSocialFlagsRequest\x1a'.cityhawk.social.v1.SocialFlagsResponse\"\x00B,Z*cityhawk/backend/pkg/pb/social/v1;socialv1b\x06proto3"

var (
	file_cityhawk_social_v1_social_proto_rawDescOnce sync.Once
	file_cityhawk_social_v1_social_proto_rawDescData []byte
)

func file_cityhawk_social_v1_social_proto_rawDescGZIP() []byte {
	file_cityhawk_social_v1_social_proto_rawDescOnce.Do(func() {
		file_cityhawk_social_v1_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cityhawk_social_v1_social_proto_rawDesc), len(file_cityhawk_social_v1_social_proto_rawDesc)))
	})
	return file_cityhawk_social_v1_social_proto_rawDescData
}

var file_cityhawk_social_v1_social_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cityhawk_social_v1_social_proto_goTypes = []any{
	(*AddFavoriteRequest)(nil),         // 0: cityhawk.social.v1.AddFavoriteRequest
	(*RemoveFavoriteRequest)(nil),      // 1: cityhawk.social.v1.RemoveFavoriteRequest
	(*ListFavoriteEventsRequest)(nil),  // 2: cityhawk.social.v1.ListFavoriteEventsRequest
	(*ListFavoriteEventsResponse)(nil), // 3: cityhawk.social.v1.ListFavoriteEventsResponse
	(*FavoriteEvent)(nil),              // 4: cityhawk.social.v1.FavoriteEvent
	(*IsFavoriteRequest)(nil),          // 5: cityhawk.social.v1.IsFavoriteRequest
	(*IsFavoriteResponse)(nil),         // 6: cityhawk.social.v1.IsFavoriteResponse
	(*FollowUserRequest)(nil),          // 7: cityhawk.social.v1.FollowUserRequest
	(*UnfollowUserRequest)(nil),        // 8: cityhawk.social.v1.UnfollowUserRequest
	(*ListFollowersRequest)(nil),       // 9: cityhawk.social.v1.ListFollowersRequest
	(*ListFollowingRequest)(nil),       // 10: cityhawk.social.v1.ListFollowingRequest
	(*ListUsersResponse)(nil),          // 11: cityhawk.social.v1.ListUsersResponse
	(*UserFollow)(nil),                 // 12: cityhawk.social.v1.UserFollow
	(*IsFollowingRequest)(nil),         // 13: cityhawk.social.v1.IsFollowingRequest
	(*IsFollowingResponse)(nil),        // 14: cityhawk.social.v1.IsFollowingResponse
	(*GetSocialFlagsRequest)(nil),      // 15: cityhawk.social.v1.GetSocialFlagsRequest
	(*EventFavoriteFlag)(nil),          // 16: cityhawk.social.v1.EventFavoriteFlag
	(*UserFollowingFlag)(nil),          // 17: cityhawk.social.v1.UserFollowingFlag
	(*SocialFlagsResponse)(nil),        // 18: cityhawk.social.v1.SocialFlagsResponse
	(*v1.UserContext)(nil),             // 19: cityhawk.common.v1.UserContext
	(*v1.PageRequest)(nil),             // 20: cityhawk.common.v1.PageRequest
	(*v1.PageResponse)(nil),            // 21: cityhawk.common.v1.PageResponse
	(*timestamppb.Timestamp)(nil),      // 22: google.protobuf.Timestamp
	(*v1.BoolResponse)(nil),            // 23: cityhawk.common.v1.BoolResponse
}
var file_cityhawk_social_v1_social_proto_depIdxs = []int32{
	19, // 0: cityhawk.social.v1.AddFavoriteRequest.actor:type_name -> cityhawk.common.v1.UserContext
	19, // 1: cityhawk.social.v1.RemoveFavoriteRequest.actor:type_name -> cityhawk.common.v1.UserContext
	19, // 2: cityhawk.social.v1.ListFavoriteEventsRequest.actor:type_name -> cityhawk.common.v1.UserContext
	20, // 3: cityhawk.social.v1.ListFavoriteEventsRequest.page:type_name -> cityhawk.common.v1.PageRequest
	4,  // 4: cityhawk.social.v1.ListFavoriteEventsResponse.items:type_name -> cityhawk.social.v1.FavoriteEvent
	21, // 5: cityhawk.social.v1.ListFavoriteEventsResponse.page:type_name -> cityhawk.common.v1.PageResponse
	22, // 6: cityhawk.social.v1.FavoriteEvent.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: cityhawk.social.v1.FollowUserRequest.actor:type_name -> cityhawk.common.v1.UserContext
	19, // 8: cityhawk.social.v1.UnfollowUserRequest.actor:type_name -> cityhawk.common.v1.UserContext
	19, // 9: cityhawk.social.v1.ListFollowersRequest.viewer_context:type_name -> cityhawk.common.v1.UserContext
	20, // 10: cityhawk.social.v1.ListFollowersRequest.page:type_name -> cityhawk.common.v1.PageRequest
	19, // 11: cityhawk.social.v1.ListFollowingRequest.viewer_context:type_name -> cityhawk.common.v1.UserContext
	20, // 12: cityhawk.social.v1.ListFollowingRequest.page:type_name -> cityhawk.common.v1.PageRequest
	12, // 13: cityhawk.social.v1.ListUsersResponse.items:type_name -> cityhawk.social.v1.UserFollow
	21, // 14: cityhawk.social.v1.ListUsersResponse.page:type_name -> cityhawk.common.v1.PageResponse
	22, // 15: cityhawk.social.v1.UserFollow.created_at:type_name -> google.protobuf.Timestamp
	19, // 16: cityhawk.social.v1.GetSocialFlagsRequest.viewer_context:type_name -> cityhawk.common.v1.UserContext
	22, // 17: cityhawk.social.v1.EventFavoriteFlag.created_at:type_name -> google.protobuf.Timestamp
	22, // 18: cityhawk.social.v1.UserFollowingFlag.created_at:type_name -> google.protobuf.Timestamp
	16, // 19: cityhawk.social.v1.SocialFlagsResponse.favorite_events:type_name -> cityhawk.social.v1.EventFavoriteFlag
	17, // 20: cityhawk.social.v1.SocialFlagsResponse.following_users:type_name -> cityhawk.social.v1.UserFollowingFlag
	0,  // 21: cityhawk.social.v1.SocialService.AddFavorite:input_type -> cityhawk.social.v1.AddFavoriteRequest
	1,  // 22: cityhawk.social.v1.SocialService.RemoveFavorite:input_type -> cityhawk.social.v1.RemoveFavoriteRequest
	2,  // 23: cityhawk.social.v1.SocialService.ListFavoriteEvents:input_type -> cityhawk.social.v1.ListFavoriteEventsRequest
	5,  // 24: cityhawk.social.v1.SocialService.IsFavorite:input_type -> cityhawk.social.v1.IsFavoriteRequest
	7,  // 25: cityhawk.social.v1.SocialService.FollowUser:input_type -> cityhawk.social.v1.FollowUserRequest
	8,  // 26: cityhawk.social.v1.SocialService.UnfollowUser:input_type -> cityhawk.social.v1.UnfollowUserRequest
	9,  // 27: cityhawk.social.v1.SocialService.ListFollowers:input_type -> cityhawk.social.v1.ListFollowersRequest
	10, // 28: cityhawk.social.v1.SocialService.ListFollowing:input_type -> cityhawk.social.v1.ListFollowingRequest
	13, // 29: cityhawk.social.v1.SocialService.IsFollowing:input_type -> cityhawk.social.v1.IsFollowingRequest
	15, // 30: cityhawk.social.v1.SocialService.GetSocialFlags:input_type -> cityhawk.social.v1.GetSocialFlagsRequest
	23, // 31: cityhawk.social.v1.SocialService.AddFavorite:output_type -> cityhawk.common.v1.BoolResponse
	23, // 32: cityhawk.social.v1.SocialService.RemoveFavorite:output_type -> cityhawk.common.v1.BoolResponse
	3,  // 33: cityhawk.social.v1.SocialService.ListFavoriteEvents:output_type -> cityhawk.social.v1.ListFavoriteEventsResponse
	6,  // 34: cityhawk.social.v1.SocialService.IsFavorite:output_type -> cityhawk.social.v1.IsFavoriteResponse
	23, // 35: cityhawk.social.v1.SocialService.FollowUser:output_type -> cityhawk.common.v1.BoolResponse
	23, // 36: cityhawk.social.v1.SocialService.UnfollowUser:output_type -> cityhawk.common.v1.BoolResponse
	11, // 37: cityhawk.social.v1.SocialService.ListFollowers:output_type -> cityhawk.social.v1.ListUsersResponse
	11, // 38: cityhawk.social.v1.SocialService.ListFollowing:output_type -> cityhawk.social.v1.ListUsersResponse
	14, // 39: cityhawk.social.v1.SocialService.IsFollowing:output_type -> cityhawk.social.v1.IsFollowingResponse
	18, // 40: cityhawk.social.v1.SocialService.GetSocialFlags:output_type -> cityhawk.social.v1.SocialFlagsResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_cityhawk_social_v1_social_proto_init() }
func file_cityhawk_social_v1_social_proto_init() {
	if File_cityhawk_social_v1_social_proto != nil {
		return
	}
	file_cityhawk_social_v1_social_proto_msgTypes[9].OneofWrappers = []any{}
	file_cityhawk_social_v1_social_proto_msgTypes[10].OneofWrappers = []any{}
	file_cityhawk_social_v1_social_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cityhawk_social_v1_social_proto_rawDesc), len(file_cityhawk_social_v1_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cityhawk_social_v1_social_proto_goTypes,
		DependencyIndexes: file_cityhawk_social_v1_social_proto_depIdxs,
		MessageInfos:      file_cityhawk_social_v1_social_proto_msgTypes,
	}.Build()
	File_cityhawk_social_v1_social_proto = out.File
	file_cityhawk_social_v1_social_proto_goTypes = nil
	file_cityhawk_social_v1_social_proto_depIdxs = nil
}
