// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: cityhawk/support/v1/support.proto

package supportv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupportService_CreateTicket_FullMethodName        = "/cityhawk.support.v1.SupportService/CreateTicket"
	SupportService_ListTickets_FullMethodName         = "/cityhawk.support.v1.SupportService/ListTickets"
	SupportService_GetTicket_FullMethodName           = "/cityhawk.support.v1.SupportService/GetTicket"
	SupportService_UpdateTicket_FullMethodName        = "/cityhawk.support.v1.SupportService/UpdateTicket"
	SupportService_UpdateTicketStatus_FullMethodName  = "/cityhawk.support.v1.SupportService/UpdateTicketStatus"
	SupportService_CreateTicketMessage_FullMethodName = "/cityhawk.support.v1.SupportService/CreateTicketMessage"
	SupportService_ListTicketMessages_FullMethodName  = "/cityhawk.support.v1.SupportService/ListTicketMessages"
	SupportService_GetTicketStats_FullMethodName      = "/cityhawk.support.v1.SupportService/GetTicketStats"
)

// SupportServiceClient is the client API for SupportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupportServiceClient interface {
	CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*Ticket, error)
	ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error)
	GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*Ticket, error)
	UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*Ticket, error)
	UpdateTicketStatus(ctx context.Context, in *UpdateTicketStatusRequest, opts ...grpc.CallOption) (*Ticket, error)
	CreateTicketMessage(ctx context.Context, in *CreateTicketMessageRequest, opts ...grpc.CallOption) (*TicketMessage, error)
	ListTicketMessages(ctx context.Context, in *ListTicketMessagesRequest, opts ...grpc.CallOption) (*ListTicketMessagesResponse, error)
	GetTicketStats(ctx context.Context, in *GetTicketStatsRequest, opts ...grpc.CallOption) (*TicketStats, error)
}

type supportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupportServiceClient(cc grpc.ClientConnInterface) SupportServiceClient {
	return &supportServiceClient{cc}
}

func (c *supportServiceClient) CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*Ticket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ticket)
	err := c.cc.Invoke(ctx, SupportService_CreateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportServiceClient) ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketsResponse)
	err := c.cc.Invoke(ctx, SupportService_ListTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportServiceClient) GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*Ticket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ticket)
	err := c.cc.Invoke(ctx, SupportService_GetTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportServiceClient) UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*Ticket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ticket)
	err := c.cc.Invoke(ctx, SupportService_UpdateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportServiceClient) UpdateTicketStatus(ctx context.Context, in *UpdateTicketStatusRequest, opts ...grpc.CallOption) (*Ticket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ticket)
	err := c.cc.Invoke(ctx, SupportService_UpdateTicketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportServiceClient) CreateTicketMessage(ctx context.Context, in *CreateTicketMessageRequest, opts ...grpc.CallOption) (*TicketMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketMessage)
	err := c.cc.Invoke(ctx, SupportService_CreateTicketMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportServiceClient) ListTicketMessages(ctx context.Context, in *ListTicketMessagesRequest, opts ...grpc.CallOption) (*ListTicketMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketMessagesResponse)
	err := c.cc.Invoke(ctx, SupportService_ListTicketMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supportServiceClient) GetTicketStats(ctx context.Context, in *GetTicketStatsRequest, opts ...grpc.CallOption) (*TicketStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketStats)
	err := c.cc.Invoke(ctx, SupportService_GetTicketStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupportServiceServer is the server API for SupportService service.
// All implementations must embed UnimplementedSupportServiceServer
// for forward compatibility.
type SupportServiceServer interface {
	CreateTicket(context.Context, *CreateTicketRequest) (*Ticket, error)
	ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error)
	GetTicket(context.Context, *GetTicketRequest) (*Ticket, error)
	UpdateTicket(context.Context, *UpdateTicketRequest) (*Ticket, error)
	UpdateTicketStatus(context.Context, *UpdateTicketStatusRequest) (*Ticket, error)
	CreateTicketMessage(context.Context, *CreateTicketMessageRequest) (*TicketMessage, error)
	ListTicketMessages(context.Context, *ListTicketMessagesRequest) (*ListTicketMessagesResponse, error)
	GetTicketStats(context.Context, *GetTicketStatsRequest) (*TicketStats, error)
	mustEmbedUnimplementedSupportServiceServer()
}

// UnimplementedSupportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupportServiceServer struct{}

func (UnimplementedSupportServiceServer) CreateTicket(context.Context, *CreateTicketRequest) (*Ticket, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicket not implemented")
}
func (UnimplementedSupportServiceServer) ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTickets not implemented")
}
func (UnimplementedSupportServiceServer) GetTicket(context.Context, *GetTicketRequest) (*Ticket, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicket not implemented")
}
func (UnimplementedSupportServiceServer) UpdateTicket(context.Context, *UpdateTicketRequest) (*Ticket, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicket not implemented")
}
func (UnimplementedSupportServiceServer) UpdateTicketStatus(context.Context, *UpdateTicketStatusRequest) (*Ticket, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTicketStatus not implemented")
}
func (UnimplementedSupportServiceServer) CreateTicketMessage(context.Context, *CreateTicketMessageRequest) (*TicketMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicketMessage not implemented")
}
func (UnimplementedSupportServiceServer) ListTicketMessages(context.Context, *ListTicketMessagesRequest) (*ListTicketMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTicketMessages not implemented")
}
func (UnimplementedSupportServiceServer) GetTicketStats(context.Context, *GetTicketStatsRequest) (*TicketStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketStats not implemented")
}
func (UnimplementedSupportServiceServer) mustEmbedUnimplementedSupportServiceServer() {}
func (UnimplementedSupportServiceServer) testEmbeddedByValue()                        {}

// UnsafeSupportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupportServiceServer will
// result in compilation errors.
type UnsafeSupportServiceServer interface {
	mustEmbedUnimplementedSupportServiceServer()
}

func RegisterSupportServiceServer(s grpc.ServiceRegistrar, srv SupportServiceServer) {
	// If the following call panics, it indicates UnimplementedSupportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupportService_ServiceDesc, srv)
}

func _SupportService_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_CreateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).CreateTicket(ctx, req.(*CreateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportService_ListTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).ListTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_ListTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).ListTickets(ctx, req.(*ListTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportService_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_GetTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).GetTicket(ctx, req.(*GetTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportService_UpdateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).UpdateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_UpdateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).UpdateTicket(ctx, req.(*UpdateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportService_UpdateTicketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).UpdateTicketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_UpdateTicketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).UpdateTicketStatus(ctx, req.(*UpdateTicketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportService_CreateTicketMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).CreateTicketMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_CreateTicketMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).CreateTicketMessage(ctx, req.(*CreateTicketMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportService_ListTicketMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).ListTicketMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_ListTicketMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).ListTicketMessages(ctx, req.(*ListTicketMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupportService_GetTicketStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportServiceServer).GetTicketStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupportService_GetTicketStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportServiceServer).GetTicketStats(ctx, req.(*GetTicketStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupportService_ServiceDesc is the grpc.ServiceDesc for SupportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cityhawk.support.v1.SupportService",
	HandlerType: (*SupportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicket",
			Handler:    _SupportService_CreateTicket_Handler,
		},
		{
			MethodName: "ListTickets",
			Handler:    _SupportService_ListTickets_Handler,
		},
		{
			MethodName: "GetTicket",
			Handler:    _SupportService_GetTicket_Handler,
		},
		{
			MethodName: "UpdateTicket",
			Handler:    _SupportService_UpdateTicket_Handler,
		},
		{
			MethodName: "UpdateTicketStatus",
			Handler:    _SupportService_UpdateTicketStatus_Handler,
		},
		{
			MethodName: "CreateTicketMessage",
			Handler:    _SupportService_CreateTicketMessage_Handler,
		},
		{
			MethodName: "ListTicketMessages",
			Handler:    _SupportService_ListTicketMessages_Handler,
		},
		{
			MethodName: "GetTicketStats",
			Handler:    _SupportService_GetTicketStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cityhawk/support/v1/support.proto",
}
