// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: cityhawk/support/v1/support.proto

package supportv1

import (
	v1 "cityhawk/backend/pkg/pb/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketCategory int32

const (
	TicketCategory_TICKET_CATEGORY_UNSPECIFIED       TicketCategory = 0
	TicketCategory_TICKET_CATEGORY_BUG               TicketCategory = 1
	TicketCategory_TICKET_CATEGORY_SUGGESTION        TicketCategory = 2
	TicketCategory_TICKET_CATEGORY_PRODUCT_COMPLAINT TicketCategory = 3
	TicketCategory_TICKET_CATEGORY_OTHER             TicketCategory = 4
)

// Enum value maps for TicketCategory.
var (
	TicketCategory_name = map[int32]string{
		0: "TICKET_CATEGORY_UNSPECIFIED",
		1: "TICKET_CATEGORY_BUG",
		2: "TICKET_CATEGORY_SUGGESTION",
		3: "TICKET_CATEGORY_PRODUCT_COMPLAINT",
		4: "TICKET_CATEGORY_OTHER",
	}
	TicketCategory_value = map[string]int32{
		"TICKET_CATEGORY_UNSPECIFIED":       0,
		"TICKET_CATEGORY_BUG":               1,
		"TICKET_CATEGORY_SUGGESTION":        2,
		"TICKET_CATEGORY_PRODUCT_COMPLAINT": 3,
		"TICKET_CATEGORY_OTHER":             4,
	}
)

func (x TicketCategory) Enum() *TicketCategory {
	p := new(TicketCategory)
	*p = x
	return p
}

func (x TicketCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_cityhawk_support_v1_support_proto_enumTypes[0].Descriptor()
}

func (TicketCategory) Type() protoreflect.EnumType {
	return &file_cityhawk_support_v1_support_proto_enumTypes[0]
}

func (x TicketCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketCategory.Descriptor instead.
func (TicketCategory) EnumDescriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{0}
}

type TicketStatus int32

const (
	TicketStatus_TICKET_STATUS_UNSPECIFIED TicketStatus = 0
	TicketStatus_TICKET_STATUS_OPEN        TicketStatus = 1
	TicketStatus_TICKET_STATUS_IN_PROGRESS TicketStatus = 2
	TicketStatus_TICKET_STATUS_CLOSED      TicketStatus = 3
)

// Enum value maps for TicketStatus.
var (
	TicketStatus_name = map[int32]string{
		0: "TICKET_STATUS_UNSPECIFIED",
		1: "TICKET_STATUS_OPEN",
		2: "TICKET_STATUS_IN_PROGRESS",
		3: "TICKET_STATUS_CLOSED",
	}
	TicketStatus_value = map[string]int32{
		"TICKET_STATUS_UNSPECIFIED": 0,
		"TICKET_STATUS_OPEN":        1,
		"TICKET_STATUS_IN_PROGRESS": 2,
		"TICKET_STATUS_CLOSED":      3,
	}
)

func (x TicketStatus) Enum() *TicketStatus {
	p := new(TicketStatus)
	*p = x
	return p
}

func (x TicketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cityhawk_support_v1_support_proto_enumTypes[1].Descriptor()
}

func (TicketStatus) Type() protoreflect.EnumType {
	return &file_cityhawk_support_v1_support_proto_enumTypes[1]
}

func (x TicketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketStatus.Descriptor instead.
func (TicketStatus) EnumDescriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{1}
}

type MessageAuthorRole int32

const (
	MessageAuthorRole_MESSAGE_AUTHOR_ROLE_UNSPECIFIED MessageAuthorRole = 0
	MessageAuthorRole_MESSAGE_AUTHOR_ROLE_USER        MessageAuthorRole = 1
	MessageAuthorRole_MESSAGE_AUTHOR_ROLE_SUPPORT     MessageAuthorRole = 2
	MessageAuthorRole_MESSAGE_AUTHOR_ROLE_ADMIN       MessageAuthorRole = 3
)

// Enum value maps for MessageAuthorRole.
var (
	MessageAuthorRole_name = map[int32]string{
		0: "MESSAGE_AUTHOR_ROLE_UNSPECIFIED",
		1: "MESSAGE_AUTHOR_ROLE_USER",
		2: "MESSAGE_AUTHOR_ROLE_SUPPORT",
		3: "MESSAGE_AUTHOR_ROLE_ADMIN",
	}
	MessageAuthorRole_value = map[string]int32{
		"MESSAGE_AUTHOR_ROLE_UNSPECIFIED": 0,
		"MESSAGE_AUTHOR_ROLE_USER":        1,
		"MESSAGE_AUTHOR_ROLE_SUPPORT":     2,
		"MESSAGE_AUTHOR_ROLE_ADMIN":       3,
	}
)

func (x MessageAuthorRole) Enum() *MessageAuthorRole {
	p := new(MessageAuthorRole)
	*p = x
	return p
}

func (x MessageAuthorRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageAuthorRole) Descriptor() protoreflect.EnumDescriptor {
	return file_cityhawk_support_v1_support_proto_enumTypes[2].Descriptor()
}

func (MessageAuthorRole) Type() protoreflect.EnumType {
	return &file_cityhawk_support_v1_support_proto_enumTypes[2]
}

func (x MessageAuthorRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageAuthorRole.Descriptor instead.
func (MessageAuthorRole) EnumDescriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{2}
}

type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      TicketCategory         `protobuf:"varint,3,opt,name=category,proto3,enum=cityhawk.support.v1.TicketCategory" json:"category,omitempty"`
	Status        TicketStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=cityhawk.support.v1.TicketStatus" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=closed_at,json=closedAt,proto3,oneof" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{0}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Ticket) GetCategory() TicketCategory {
	if x != nil {
		return x.Category
	}
	return TicketCategory_TICKET_CATEGORY_UNSPECIFIED
}

func (x *Ticket) GetStatus() TicketStatus {
	if x != nil {
		return x.Status
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *Ticket) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ticket) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ticket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ticket) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Ticket) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

type TicketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	AuthorUserId  string                 `protobuf:"bytes,3,opt,name=author_user_id,json=authorUserId,proto3" json:"author_user_id,omitempty"`
	AuthorRole    MessageAuthorRole      `protobuf:"varint,4,opt,name=author_role,json=authorRole,proto3,enum=cityhawk.support.v1.MessageAuthorRole" json:"author_role,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketMessage) Reset() {
	*x = TicketMessage{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketMessage) ProtoMessage() {}

func (x *TicketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketMessage.ProtoReflect.Descriptor instead.
func (*TicketMessage) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{1}
}

func (x *TicketMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TicketMessage) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *TicketMessage) GetAuthorUserId() string {
	if x != nil {
		return x.AuthorUserId
	}
	return ""
}

func (x *TicketMessage) GetAuthorRole() MessageAuthorRole {
	if x != nil {
		return x.AuthorRole
	}
	return MessageAuthorRole_MESSAGE_AUTHOR_ROLE_UNSPECIFIED
}

func (x *TicketMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TicketMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Category      TicketCategory         `protobuf:"varint,2,opt,name=category,proto3,enum=cityhawk.support.v1.TicketCategory" json:"category,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTicketRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *CreateTicketRequest) GetCategory() TicketCategory {
	if x != nil {
		return x.Category
	}
	return TicketCategory_TICKET_CATEGORY_UNSPECIFIED
}

func (x *CreateTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTicketRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Status        *TicketStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=cityhawk.support.v1.TicketStatus,oneof" json:"status,omitempty"`
	Category      *TicketCategory        `protobuf:"varint,3,opt,name=category,proto3,enum=cityhawk.support.v1.TicketCategory,oneof" json:"category,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{3}
}

func (x *ListTicketsRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ListTicketsRequest) GetStatus() TicketStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

func (x *ListTicketsRequest) GetCategory() TicketCategory {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return TicketCategory_TICKET_CATEGORY_UNSPECIFIED
}

func (x *ListTicketsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Ticket              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{4}
}

func (x *ListTicketsResponse) GetItems() []*Ticket {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListTicketsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{5}
}

func (x *GetTicketRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *GetTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type UpdateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Category      *TicketCategory        `protobuf:"varint,3,opt,name=category,proto3,enum=cityhawk.support.v1.TicketCategory,oneof" json:"category,omitempty"`
	Title         *string                `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Message       *string                `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketRequest) Reset() {
	*x = UpdateTicketRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketRequest) ProtoMessage() {}

func (x *UpdateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTicketRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *UpdateTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *UpdateTicketRequest) GetCategory() TicketCategory {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return TicketCategory_TICKET_CATEGORY_UNSPECIFIED
}

func (x *UpdateTicketRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateTicketRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type UpdateTicketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        TicketStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=cityhawk.support.v1.TicketStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketStatusRequest) Reset() {
	*x = UpdateTicketStatusRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketStatusRequest) ProtoMessage() {}

func (x *UpdateTicketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTicketStatusRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTicketStatusRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *UpdateTicketStatusRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *UpdateTicketStatusRequest) GetStatus() TicketStatus {
	if x != nil {
		return x.Status
	}
	return TicketStatus_TICKET_STATUS_UNSPECIFIED
}

type CreateTicketMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketMessageRequest) Reset() {
	*x = CreateTicketMessageRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketMessageRequest) ProtoMessage() {}

func (x *CreateTicketMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketMessageRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTicketMessageRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *CreateTicketMessageRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CreateTicketMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ListTicketMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketMessagesRequest) Reset() {
	*x = ListTicketMessagesRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketMessagesRequest) ProtoMessage() {}

func (x *ListTicketMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListTicketMessagesRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{9}
}

func (x *ListTicketMessagesRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ListTicketMessagesRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type ListTicketMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TicketMessage       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketMessagesResponse) Reset() {
	*x = ListTicketMessagesResponse{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketMessagesResponse) ProtoMessage() {}

func (x *ListTicketMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListTicketMessagesResponse) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{10}
}

func (x *ListTicketMessagesResponse) GetItems() []*TicketMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetTicketStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *v1.UserContext        `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3,oneof" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketStatsRequest) Reset() {
	*x = GetTicketStatsRequest{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketStatsRequest) ProtoMessage() {}

func (x *GetTicketStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketStatsRequest.ProtoReflect.Descriptor instead.
func (*GetTicketStatsRequest) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{11}
}

func (x *GetTicketStatsRequest) GetActor() *v1.UserContext {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *GetTicketStatsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetTicketStatsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type TicketStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Total           int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	ByStatus        map[string]int32       `protobuf:"bytes,2,rep,name=by_status,json=byStatus,proto3" json:"by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByCategory      map[string]int32       `protobuf:"bytes,3,rep,name=by_category,json=byCategory,proto3" json:"by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	OpenTotal       int32                  `protobuf:"varint,4,opt,name=open_total,json=openTotal,proto3" json:"open_total,omitempty"`
	InProgressTotal int32                  `protobuf:"varint,5,opt,name=in_progress_total,json=inProgressTotal,proto3" json:"in_progress_total,omitempty"`
	ClosedTotal     int32                  `protobuf:"varint,6,opt,name=closed_total,json=closedTotal,proto3" json:"closed_total,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TicketStats) Reset() {
	*x = TicketStats{}
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketStats) ProtoMessage() {}

func (x *TicketStats) ProtoReflect() protoreflect.Message {
	mi := &file_cityhawk_support_v1_support_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketStats.ProtoReflect.Descriptor instead.
func (*TicketStats) Descriptor() ([]byte, []int) {
	return file_cityhawk_support_v1_support_proto_rawDescGZIP(), []int{12}
}

func (x *TicketStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TicketStats) GetByStatus() map[string]int32 {
	if x != nil {
		return x.ByStatus
	}
	return nil
}

func (x *TicketStats) GetByCategory() map[string]int32 {
	if x != nil {
		return x.ByCategory
	}
	return nil
}

func (x *TicketStats) GetOpenTotal() int32 {
	if x != nil {
		return x.OpenTotal
	}
	return 0
}

func (x *TicketStats) GetInProgressTotal() int32 {
	if x != nil {
		return x.InProgressTotal
	}
	return 0
}

func (x *TicketStats) GetClosedTotal() int32 {
	if x != nil {
		return x.ClosedTotal
	}
	return 0
}

var File_cityhawk_support_v1_support_proto protoreflect.FileDescriptor

const file_cityhawk_support_v1_support_proto_rawDesc = "" +
	"\n" +
	"!cityhawk/support/v1/support.proto\x12\x13cityhawk.support.v1\x1a\x1fcityhawk/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x03\n" +
	"\x06Ticket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12?\n" +
	"\bcategory\x18\x03 \x01(\x0e2#.cityhawk.support.v1.TicketCategoryR\bcategory\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.cityhawk.support.v1.TicketStatusR\x06status\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\tclosed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bclosedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_closed_at\"\xfa\x01\n" +
	"\rTicketMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12$\n" +
	"\x0eauthor_user_id\x18\x03 \x01(\tR\fauthorUserId\x12G\n" +
	"\vauthor_role\x18\x04 \x01(\x0e2&.cityhawk.support.v1.MessageAuthorRoleR\n" +
	"authorRole\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbd\x01\n" +
	"\x13CreateTicketRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12?\n" +
	"\bcategory\x18\x02 \x01(\x0e2#.cityhawk.support.v1.TicketCategoryR\bcategory\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x9e\x02\n" +
	"\x12ListTicketsRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2!.cityhawk.support.v1.TicketStatusH\x00R\x06status\x88\x01\x01\x12D\n" +
	"\bcategory\x18\x03 \x01(\x0e2#.cityhawk.support.v1.TicketCategoryH\x01R\bcategory\x88\x01\x01\x123\n" +
	"\x04page\x18\x04 \x01(\v2\x1f.cityhawk.common.v1.PageRequestR\x04pageB\t\n" +
	"\a_statusB\v\n" +
	"\t_category\"~\n" +
	"\x13ListTicketsResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.cityhawk.support.v1.TicketR\x05items\x124\n" +
	"\x04page\x18\x02 \x01(\v2 .cityhawk.common.v1.PageResponseR\x04page\"f\n" +
	"\x10GetTicketRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\"\x8c\x02\n" +
	"\x13UpdateTicketRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12D\n" +
	"\bcategory\x18\x03 \x01(\x0e2#.cityhawk.support.v1.TicketCategoryH\x00R\bcategory\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x05 \x01(\tH\x02R\amessage\x88\x01\x01B\v\n" +
	"\t_categoryB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_message\"\xaa\x01\n" +
	"\x19UpdateTicketStatusRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.cityhawk.support.v1.TicketStatusR\x06status\"\x84\x01\n" +
	"\x1aCreateTicketMessageRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"o\n" +
	"\x19ListTicketMessagesRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\"V\n" +
	"\x1aListTicketMessagesResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".cityhawk.support.v1.TicketMessageR\x05items\"\xc4\x01\n" +
	"\x15GetTicketStatsRequest\x125\n" +
	"\x05actor\x18\x01 \x01(\v2\x1f.cityhawk.common.v1.UserContextR\x05actor\x123\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01B\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"\xad\x03\n" +
	"\vTicketStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12K\n" +
	"\tby_status\x18\x02 \x03(\v2..cityhawk.support.v1.TicketStats.ByStatusEntryR\bbyStatus\x12Q\n" +
	"\vby_category\x18\x03 \x03(\v20.cityhawk.support.v1.TicketStats.ByCategoryEntryR\n" +
	"byCategory\x12\x1d\n" +
	"\n" +
	"open_total\x18\x04 \x01(\x05R\topenTotal\x12*\n" +
	"\x11in_progress_total\x18\x05 \x01(\x05R\x0finProgressTotal\x12!\n" +
	"\fclosed_total\x18\x06 \x01(\x05R\vclosedTotal\x1a;\n" +
	"\rByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*\xac\x01\n" +
	"\x0eTicketCategory\x12\x1f\n" +
	"\x1bTICKET_CATEGORY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TICKET_CATEGORY_BUG\x10\x01\x12\x1e\n" +
	"\x1aTICKET_CATEGORY_SUGGESTION\x10\x02\x12%\n" +
	"!TICKET_CATEGORY_PRODUCT_COMPLAINT\x10\x03\x12\x19\n" +
	"\x15TICKET_CATEGORY_OTHER\x10\x04*~\n" +
	"\fTicketStatus\x12\x1d\n" +
	"\x19TICKET_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TICKET_STATUS_OPEN\x10\x01\x12\x1d\n" +
	"\x19TICKET_STATUS_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14TICKET_STATUS_CLOSED\x10\x03*\x96\x01\n" +
	"\x11MessageAuthorRole\x12#\n" +
	"\x1fMESSAGE_AUTHOR_ROLE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MESSAGE_AUTHOR_ROLE_USER\x10\x01\x12\x1f\n" +
	"\x1bMESSAGE_AUTHOR_ROLE_SUPPORT\x10\x02\x12\x1d\n" +
	"\x19MESSAGE_AUTHOR_ROLE_ADMIN\x10\x032\xa7\x06\n" +
	"\x0eSupportService\x12W\n" +
	"\fCreateTicket\x12(.cityhawk.support.v1.CreateTicketRequest\x1a\x1b.cityhawk.support.v1.Ticket\"\x00\x12b\n" +
	"\vListTickets\x12'.cityhawk.support.v1.ListTicketsRequest\x1a(.cityhawk.support.v1.ListTicketsResponse\"\x00\x12Q\n" +
	"\tGetTicket\x12%.cityhawk.support.v1.GetTicketRequest\x1a\x1b.cityhawk.support.v1.Ticket\"\x00\x12W\n" +
	"\fUpdateTicket\x12(.cityhawk.support.v1.UpdateTicketRequest\x1a\x1b.cityhawk.support.v1.Ticket\"\x00\x12c\n" +
	"\x12UpdateTicketStatus\x12..cityhawk.support.v1.UpdateTicketStatusRequest\x1a\x1b.cityhawk.support.v1.Ticket\"\x00\x12l\n" +
	"\x13CreateTicketMessage\x12/.cityhawk.support.v1.CreateTicketMessageRequest\x1a\".cityhawk.support.v1.TicketMessage\"\x00\x12w\n" +
	"\x12ListTicketMessages\x12..cityhawk.support.v1.ListTicketMessagesRequest\x1a/.cityhawk.support.v1.ListTicketMessagesResponse\"\x00\x12`\n" +
	"\x0eGetTicketStats\x12*.cityhawk.support.v1.GetTicketStatsRequest\x1a .cityhawk.support.v1.TicketStats\"\x00B.Z,cityhawk/backend/pkg/pb/support/v1;supportv1b\x06proto3"

var (
	file_cityhawk_support_v1_support_proto_rawDescOnce sync.Once
	file_cityhawk_support_v1_support_proto_rawDescData []byte
)

func file_cityhawk_support_v1_support_proto_rawDescGZIP() []byte {
	file_cityhawk_support_v1_support_proto_rawDescOnce.Do(func() {
		file_cityhawk_support_v1_support_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cityhawk_support_v1_support_proto_rawDesc), len(file_cityhawk_support_v1_support_proto_rawDesc)))
	})
	return file_cityhawk_support_v1_support_proto_rawDescData
}

var file_cityhawk_support_v1_support_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cityhawk_support_v1_support_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cityhawk_support_v1_support_proto_goTypes = []any{
	(TicketCategory)(0),                // 0: cityhawk.support.v1.TicketCategory
	(TicketStatus)(0),                  // 1: cityhawk.support.v1.TicketStatus
	(MessageAuthorRole)(0),             // 2: cityhawk.support.v1.MessageAuthorRole
	(*Ticket)(nil),                     // 3: cityhawk.support.v1.Ticket
	(*TicketMessage)(nil),              // 4: cityhawk.support.v1.TicketMessage
	(*CreateTicketRequest)(nil),        // 5: cityhawk.support.v1.CreateTicketRequest
	(*ListTicketsRequest)(nil),         // 6: cityhawk.support.v1.ListTicketsRequest
	(*ListTicketsResponse)(nil),        // 7: cityhawk.support.v1.ListTicketsResponse
	(*GetTicketRequest)(nil),           // 8: cityhawk.support.v1.GetTicketRequest
	(*UpdateTicketRequest)(nil),        // 9: cityhawk.support.v1.UpdateTicketRequest
	(*UpdateTicketStatusRequest)(nil),  // 10: cityhawk.support.v1.UpdateTicketStatusRequest
	(*CreateTicketMessageRequest)(nil), // 11: cityhawk.support.v1.CreateTicketMessageRequest
	(*ListTicketMessagesRequest)(nil),  // 12: cityhawk.support.v1.ListTicketMessagesRequest
	(*ListTicketMessagesResponse)(nil), // 13: cityhawk.support.v1.ListTicketMessagesResponse
	(*GetTicketStatsRequest)(nil),      // 14: cityhawk.support.v1.GetTicketStatsRequest
	(*TicketStats)(nil),                // 15: cityhawk.support.v1.TicketStats
	nil,                                // 16: cityhawk.support.v1.TicketStats.ByStatusEntry
	nil,                                // 17: cityhawk.support.v1.TicketStats.ByCategoryEntry
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
	(*v1.UserContext)(nil),             // 19: cityhawk.common.v1.UserContext
	(*v1.PageRequest)(nil),             // 20: cityhawk.common.v1.PageRequest
	(*v1.PageResponse)(nil),            // 21: cityhawk.common.v1.PageResponse
}
var file_cityhawk_support_v1_support_proto_depIdxs = []int32{
	0,  // 0: cityhawk.support.v1.Ticket.category:type_name -> cityhawk.support.v1.TicketCategory
	1,  // 1: cityhawk.support.v1.Ticket.status:type_name -> cityhawk.support.v1.TicketStatus
	18, // 2: cityhawk.support.v1.Ticket.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: cityhawk.support.v1.Ticket.updated_at:type_name -> google.protobuf.Timestamp
	18, // 4: cityhawk.support.v1.Ticket.closed_at:type_name -> google.protobuf.Timestamp
	2,  // 5: cityhawk.support.v1.TicketMessage.author_role:type_name -> cityhawk.support.v1.MessageAuthorRole
	18, // 6: cityhawk.support.v1.TicketMessage.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: cityhawk.support.v1.CreateTicketRequest.actor:type_name -> cityhawk.common.v1.UserContext
	0,  // 8: cityhawk.support.v1.CreateTicketRequest.category:type_name -> cityhawk.support.v1.TicketCategory
	19, // 9: cityhawk.support.v1.ListTicketsRequest.actor:type_name -> cityhawk.common.v1.UserContext
	1,  // 10: cityhawk.support.v1.ListTicketsRequest.status:type_name -> cityhawk.support.v1.TicketStatus
	0,  // 11: cityhawk.support.v1.ListTicketsRequest.category:type_name -> cityhawk.support.v1.TicketCategory
	20, // 12: cityhawk.support.v1.ListTicketsRequest.page:type_name -> cityhawk.common.v1.PageRequest
	3,  // 13: cityhawk.support.v1.ListTicketsResponse.items:type_name -> cityhawk.support.v1.Ticket
	21, // 14: cityhawk.support.v1.ListTicketsResponse.page:type_name -> cityhawk.common.v1.PageResponse
	19, // 15: cityhawk.support.v1.GetTicketRequest.actor:type_name -> cityhawk.common.v1.UserContext
	19, // 16: cityhawk.support.v1.UpdateTicketRequest.actor:type_name -> cityhawk.common.v1.UserContext
	0,  // 17: cityhawk.support.v1.UpdateTicketRequest.category:type_name -> cityhawk.support.v1.TicketCategory
	19, // 18: cityhawk.support.v1.UpdateTicketStatusRequest.actor:type_name -> cityhawk.common.v1.UserContext
	1,  // 19: cityhawk.support.v1.UpdateTicketStatusRequest.status:type_name -> cityhawk.support.v1.TicketStatus
	19, // 20: cityhawk.support.v1.CreateTicketMessageRequest.actor:type_name -> cityhawk.common.v1.UserContext
	19, // 21: cityhawk.support.v1.ListTicketMessagesRequest.actor:type_name -> cityhawk.common.v1.UserContext
	4,  // 22: cityhawk.support.v1.ListTicketMessagesResponse.items:type_name -> cityhawk.support.v1.TicketMessage
	19, // 23: cityhawk.support.v1.GetTicketStatsRequest.actor:type_name -> cityhawk.common.v1.UserContext
	18, // 24: cityhawk.support.v1.GetTicketStatsRequest.from:type_name -> google.protobuf.Timestamp
	18, // 25: cityhawk.support.v1.GetTicketStatsRequest.to:type_name -> google.protobuf.Timestamp
	16, // 26: cityhawk.support.v1.TicketStats.by_status:type_name -> cityhawk.support.v1.TicketStats.ByStatusEntry
	17, // 27: cityhawk.support.v1.TicketStats.by_category:type_name -> cityhawk.support.v1.TicketStats.ByCategoryEntry
	5,  // 28: cityhawk.support.v1.SupportService.CreateTicket:input_type -> cityhawk.support.v1.CreateTicketRequest
	6,  // 29: cityhawk.support.v1.SupportService.ListTickets:input_type -> cityhawk.support.v1.ListTicketsRequest
	8,  // 30: cityhawk.support.v1.SupportService.GetTicket:input_type -> cityhawk.support.v1.GetTicketRequest
	9,  // 31: cityhawk.support.v1.SupportService.UpdateTicket:input_type -> cityhawk.support.v1.UpdateTicketRequest
	10, // 32: cityhawk.support.v1.SupportService.UpdateTicketStatus:input_type -> cityhawk.support.v1.UpdateTicketStatusRequest
	11, // 33: cityhawk.support.v1.SupportService.CreateTicketMessage:input_type -> cityhawk.support.v1.CreateTicketMessageRequest
	12, // 34: cityhawk.support.v1.SupportService.ListTicketMessages:input_type -> cityhawk.support.v1.ListTicketMessagesRequest
	14, // 35: cityhawk.support.v1.SupportService.GetTicketStats:input_type -> cityhawk.support.v1.GetTicketStatsRequest
	3,  // 36: cityhawk.support.v1.SupportService.CreateTicket:output_type -> cityhawk.support.v1.Ticket
	7,  // 37: cityhawk.support.v1.SupportService.ListTickets:output_type -> cityhawk.support.v1.ListTicketsResponse
	3,  // 38: cityhawk.support.v1.SupportService.GetTicket:output_type -> cityhawk.support.v1.Ticket
	3,  // 39: cityhawk.support.v1.SupportService.UpdateTicket:output_type -> cityhawk.support.v1.Ticket
	3,  // 40: cityhawk.support.v1.SupportService.UpdateTicketStatus:output_type -> cityhawk.support.v1.Ticket
	4,  // 41: cityhawk.support.v1.SupportService.CreateTicketMessage:output_type -> cityhawk.support.v1.TicketMessage
	13, // 42: cityhawk.support.v1.SupportService.ListTicketMessages:output_type -> cityhawk.support.v1.ListTicketMessagesResponse
	15, // 43: cityhawk.support.v1.SupportService.GetTicketStats:output_type -> cityhawk.support.v1.TicketStats
	36, // [36:44] is the sub-list for method output_type
	28, // [28:36] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_cityhawk_support_v1_support_proto_init() }
func file_cityhawk_support_v1_support_proto_init() {
	if File_cityhawk_support_v1_support_proto != nil {
		return
	}
	file_cityhawk_support_v1_support_proto_msgTypes[0].OneofWrappers = []any{}
	file_cityhawk_support_v1_support_proto_msgTypes[3].OneofWrappers = []any{}
	file_cityhawk_support_v1_support_proto_msgTypes[6].OneofWrappers = []any{}
	file_cityhawk_support_v1_support_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cityhawk_support_v1_support_proto_rawDesc), len(file_cityhawk_support_v1_support_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cityhawk_support_v1_support_proto_goTypes,
		DependencyIndexes: file_cityhawk_support_v1_support_proto_depIdxs,
		EnumInfos:         file_cityhawk_support_v1_support_proto_enumTypes,
		MessageInfos:      file_cityhawk_support_v1_support_proto_msgTypes,
	}.Build()
	File_cityhawk_support_v1_support_proto = out.File
	file_cityhawk_support_v1_support_proto_goTypes = nil
	file_cityhawk_support_v1_support_proto_depIdxs = nil
}
