// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package http

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeCityhawkBackendInternalUserDeliveryHttp(in *jlexer.Lexer, out *patchMeRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Email = string(in.String())
				}
			}
		case "username":
			if in.IsNull() {
				in.Skip()
				out.Username = nil
			} else {
				if out.Username == nil {
					out.Username = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Username = string(in.String())
				}
			}
		case "userSurname":
			if in.IsNull() {
				in.Skip()
				out.UserSurname = nil
			} else {
				if out.UserSurname == nil {
					out.UserSurname = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.UserSurname = string(in.String())
				}
			}
		case "birthday":
			if in.IsNull() {
				in.Skip()
				out.Birthday = nil
			} else {
				if out.Birthday == nil {
					out.Birthday = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Birthday = string(in.String())
				}
			}
		case "cityId":
			if in.IsNull() {
				in.Skip()
				out.CityID = nil
			} else {
				if out.CityID == nil {
					out.CityID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.CityID = string(in.String())
				}
			}
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Bio = string(in.String())
				}
			}
		case "interestTagIds":
			if in.IsNull() {
				in.Skip()
				out.InterestTagIDs = nil
			} else {
				in.Delim('[')
				if out.InterestTagIDs == nil {
					if !in.IsDelim(']') {
						out.InterestTagIDs = make([]string, 0, 4)
					} else {
						out.InterestTagIDs = []string{}
					}
				} else {
					out.InterestTagIDs = (out.InterestTagIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.InterestTagIDs = append(out.InterestTagIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "avatarUrl":
			if in.IsNull() {
				in.Skip()
				out.AvatarURL = nil
			} else {
				if out.AvatarURL == nil {
					out.AvatarURL = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarURL = string(in.String())
				}
			}
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeCityhawkBackendInternalUserDeliveryHttp(out *jwriter.Writer, in patchMeRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix[1:])
		if in.Email == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Email))
		}
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		if in.Username == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Username))
		}
	}
	{
		const prefix string = ",\"userSurname\":"
		out.RawString(prefix)
		if in.UserSurname == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.UserSurname))
		}
	}
	{
		const prefix string = ",\"birthday\":"
		out.RawString(prefix)
		if in.Birthday == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Birthday))
		}
	}
	{
		const prefix string = ",\"cityId\":"
		out.RawString(prefix)
		if in.CityID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CityID))
		}
	}
	{
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		if in.Bio == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Bio))
		}
	}
	{
		const prefix string = ",\"interestTagIds\":"
		out.RawString(prefix)
		if in.InterestTagIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.InterestTagIDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"avatarUrl\":"
		out.RawString(prefix)
		if in.AvatarURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarURL))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v patchMeRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeCityhawkBackendInternalUserDeliveryHttp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v patchMeRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeCityhawkBackendInternalUserDeliveryHttp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *patchMeRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeCityhawkBackendInternalUserDeliveryHttp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *patchMeRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeCityhawkBackendInternalUserDeliveryHttp(l, v)
}
